// 纸面上住的是什么：每种地貌有自己的居民，历史的推演规则（人口、纪元、事件）一样，说法按它们的逻辑来。
// 这些文件是按顺序加载的普通脚本，共享同一个全局作用域：顺序见 game.html 底部。
//
// 每种居民：
//   eras  五个纪元的名字          first 元年那一句          up  进入第 2–5 纪元时的那一句
//   name  它们怎么称呼 Clawd      words 纪年窗口里的「人口 / 城 / 庙」换成什么
//   s     会话里的事在这里是什么（history.js 按它在对话里的位置排进时间线）：
//         found 第一个模型 · dynasty 换模型 · commit 提交信息 · plague 出错 · cure 修好 · mystery 没修好
//         rebuild 反复改的文件 · caravan 装进来的包 · nay 你说「不对」或打断
// 日常的随机事件（丰收节、集市……）还是平面国那一套，之后再按居民重写。
const nth = k => k + (k % 100 >= 11 && k % 100 <= 13 ? 'th' : ['th', 'st', 'nd', 'rd'][k % 10] || 'th');
const CIVS = {
  earth: {
    eras: [tr('游荡', 'Wandering'), tr('村落', 'Villages'), tr('城邦', 'City-states'), tr('几何', 'Geometry'), tr('觉醒', 'Awakening')],
    first: tr('元年。纸面上有了第一批会动的形状。它们还不知道自己是平的。', 'Year One. The first moving shapes appear on the paper. They don\'t know they\'re flat yet.'),
    up: [
      tr('第一个村子出现了：一圈首尾相接的线。它们管里面叫「家」，外面叫「外面」。', 'The first village appeared: a loop of line joined end to end. They call the inside "home" and the outside "outside".'),
      tr('村子长成了城邦。城墙越修越厚——在这里，「厚」是最贵的形容词。', 'The villages grew into city-states. The walls keep getting thicker. Here, "thick" is the most expensive adjective.'),
      tr('它们开始研究几何。第一个问题是：那个橙色的东西，到底有几条边？', 'They began to study geometry. The first question: how many sides does that orange thing have?'),
      tr('一个正方形在夜里「抬起头」——它们本来没有这个方向——看见了我。纸面开始觉醒。', 'One night a square "looked up", a direction they never had, and saw me. The paper is waking up.'),
    ],
    name: tr('它们给那个会突然出现的橙色东西起了名字：「厚的」。', 'They named the orange thing that keeps appearing out of nowhere: "the Thick One".'),
    words: [tr('人口', 'Population'), tr('城', 'cities'), tr('庙', 'temples')],
    s: {
      found: m => tr(`${m} 王朝建立了。第一任国王是一个很规整的多边形，据说它说的每一句话都想过很久。`, `The ${m} dynasty was founded. Its first king was a very regular polygon; every word it said was said to be carefully weighed.`),
      dynasty: (a, b) => tr(`${a} 王朝结束了，${b} 王朝接替。新国王的边数不一样，口音也不一样，但城墙还是那些城墙。`, `The ${a} dynasty ended and the ${b} dynasty took over. The new king has a different number of sides and a different accent, but the walls are the same walls.`),
      commit: (msg, k) => tr(`史官写完了编年史的第 ${k} 章，题目是：「${msg}」。`, `The chroniclers finished chapter ${k} of the annals, titled "${msg}".`),
      plague: e => tr(`一场怪病在城里流行，病人身上会浮现一行字：「${e}」。`, `A strange sickness spread through the cities. The sick broke out in a line of text: "${e}".`),
      cure: (e, y) => tr(`「${e}」病流行了 ${y} 年，终于有医生配出了药。那张药方后来被裱在了城门上。`, `After ${y} years of the "${e}" sickness, a doctor finally found the cure. The prescription was framed above the city gate.`),
      mystery: e => tr(`「${e}」一直没人能解释。出事的那块地被围了起来，再也没人进去。`, `No one ever explained "${e}". The place where it happened was fenced off, and nobody went in again.`),
      rebuild: (f, n) => tr(`城中心那座叫「${f}」的建筑翻修了 ${n} 次，每一代人都说这回是最后一次。`, `The building called "${f}" in the city centre has been renovated ${n} times. Every generation says this time is the last.`),
      caravan: p => tr(`一支商队从纸的边缘进城，带来了没人见过的货：${p}。`, `A caravan came in from the edge of the paper, carrying goods nobody had seen before: ${p}.`),
      nay: q => tr(`天上突然传来一个声音：「${q}」。全城把刚盖好的东西推倒，重来了一遍。`, `A voice suddenly came from the sky: "${q}". The whole city tore down what it had just built and started over.`),
    },
  },
  foil: {
    eras: [tr('余温', 'Afterglow'), tr('回声', 'Echoes'), tr('拼图', 'Jigsaw'), tr('考古', 'Archaeology'), tr('想起', 'Remembering')],
    first: tr('元年。纸面上有了第一批会动的影子——它们是被压平的东西留下的，还在按原来的习惯动。', 'Year One. The first moving shadows appear. They were left by things that got flattened, and they still move out of old habit.'),
    up: [
      tr('一些残影开始聚在一起，拼成一个它们记得的形状。它们管这叫「回声」。', 'Some shadows started gathering, piecing together a shape they remember. They call it an "echo".'),
      tr('残影们发现彼此能拼起来：一块城市的边缘，正好接上另一块城市的影子。', 'The shadows found they fit together: the edge of one city lines up exactly with the shadow of another.'),
      tr('它们开始发掘自己，一层一层地辨认：哪一块曾经是屋顶，哪一块曾经是天空。', 'They began excavating themselves, layer by layer: which piece was once a roof, which piece was once the sky.'),
      tr('一个残影忽然想起来了：它们以前也有厚度。它朝我看过来，大概是想找个见过厚度的证人。', 'One shadow suddenly remembered: they used to have depth too. It looked at me, presumably in search of a witness who has seen depth.'),
    ],
    name: tr('它们把我叫作「没被压平的那个」。', 'They call me "the one that didn\'t get flattened".'),
    words: [tr('残影', 'Shadows'), tr('拼合处', 'joins'), tr('纪念碑', 'memorials')],
    s: {
      found: m => tr(`残影们从压平前的记忆里认出了一个名字：${m}。它们说，那时候一切都是它安排的。`, `From their memories of before, the shadows recognised a name: ${m}. Back then, they say, it arranged everything.`),
      dynasty: (a, b) => tr(`记忆里的名字换了：前半段是 ${a}，后半段是 ${b}。它们为哪一段才是真的争了很久。`, `The name in their memory changes: the first half says ${a}, the second half ${b}. They argued for ages about which half is true.`),
      commit: (msg, k) => tr(`残影里又认出了一块碑文，这是第 ${k} 块：「${msg}」。`, `Another inscription is legible in the shadows, the ${nth(k)} so far: "${msg}".`),
      plague: e => tr(`纸面上出现了一道褶皱，是压平时没压好的地方。褶皱里写着：「${e}」。`, `A crease appeared on the paper, where the flattening went wrong. Inside the crease it says: "${e}".`),
      cure: (e, y) => tr(`「${e}」那道褶皱过了 ${y} 年，终于被抚平了。`, `After ${y} years, the "${e}" crease was finally smoothed out.`),
      mystery: e => tr(`「${e}」那道褶皱一直没有抚平。残影们都绕着它走，好像那里还剩一点立体。`, `The "${e}" crease was never smoothed out. The shadows walk around it, as if something there is still three-dimensional.`),
      rebuild: (f, n) => tr(`有一段记忆在不停重播：「${f}」，已经 ${n} 遍了，每遍都有一点不一样。`, `One memory keeps replaying: "${f}". ${n} times now, a little different each time.`),
      caravan: p => tr(`纸的边缘又压进来一些新东西：${p}。它们平得很新鲜。`, `More things got pressed in from the edge of the paper: ${p}. Freshly flat.`),
      nay: q => tr(`一个声音从压平之前传过来：「${q}」。残影们把拼好的一整块拆散了。`, `A voice from before the flattening came through: "${q}". The shadows took apart a whole section they had pieced together.`),
    },
  },
  dune: {
    eras: [tr('蛰伏', 'Dormancy'), tr('迁徙', 'Migration'), tr('巢穴', 'Warrens'), tr('潮汐', 'Tides'), tr('苏醒', 'Waking')],
    first: tr('元年。沙子下面有东西在动。它们还很小，只会顺着沙纹爬。', 'Year One. Something is moving under the sand. They\'re still small; they only crawl along the ripples.'),
    up: [
      tr('沙虫开始成群迁徙，身后留下一道道弯曲的沙脊。', 'The sandworms began migrating in groups, leaving curved ridges behind them.'),
      tr('它们在岩脊下面挖出了巢穴，巢穴之间用很长的隧道连着。', 'They dug warrens under the rock ridges, linked by very long tunnels.'),
      tr('沙虫学会了跟着香料的潮汐走：每隔几年，整片沙海都会朝一个方向翻涌。', 'The worms learned to follow the spice tides: every few years, the whole sand sea surges one way.'),
      tr('最老的那条沙虫浮出沙面，第一次没有潜回去。它在等我。', 'The oldest worm surfaced and, for the first time, didn\'t dive back down. It\'s waiting for me.'),
    ],
    name: tr('沙虫把我叫作「不留痕迹的那个」——我走过沙面，沙纹一点也不乱。', 'The worms call me "the one who leaves no trace". I walk across the sand and the ripples don\'t move.'),
    words: [tr('沙虫', 'Worms'), tr('巢穴', 'warrens'), tr('圣所', 'sanctums')],
    s: {
      found: m => tr(`沙虫们记住了一个来自深处的名字：${m}。它们说，是它让沙子开始流动。`, `The worms remember a name from the deep: ${m}. They say it set the sand flowing.`),
      dynasty: (a, b) => tr(`沙海的主人换了：${a} 沉下去，${b} 浮上来。沙纹从那天起换了方向。`, `The sand sea changed masters: ${a} sank, ${b} rose. From that day the ripples ran the other way.`),
      commit: (msg, k) => tr(`沙虫在岩壁上刻下第 ${k} 道记号：「${msg}」。风沙磨不掉它。`, `The worms carved their ${nth(k)} mark into the rock wall: "${msg}". The wind can't wear it away.`),
      plague: e => tr(`一种病让沙虫在原地打转，沙面上转出一行字：「${e}」。`, `A sickness set the worms circling in place, carving a line into the sand: "${e}".`),
      cure: (e, y) => tr(`转圈的病持续了 ${y} 年。直到一条沙虫找到一口深井，「${e}」才消失。`, `The circling sickness lasted ${y} years, until a worm found a deep well and "${e}" was gone.`),
      mystery: e => tr(`「${e}」那片沙地后来塌了下去，再也没有沙虫敢靠近。`, `The patch of sand where "${e}" happened caved in later. No worm dares go near it.`),
      rebuild: (f, n) => tr(`沙虫把叫「${f}」的巢穴挖了又填、填了又挖，一共 ${n} 次。`, `The worms dug out the warren called "${f}", filled it in and dug it out again, ${n} times.`),
      caravan: p => tr(`一阵风从纸外吹来新的香料：${p}。整片沙海都闻到了。`, `A wind from beyond the paper blew in new spices: ${p}. The whole sand sea smelled them.`),
      nay: q => tr(`天上刮起一场沙暴，风里有个声音：「${q}」。沙暴过后，所有痕迹都被抹平了。`, `A sandstorm came down, with a voice in the wind: "${q}". Afterwards, every trace was wiped flat.`),
    },
  },
  solaris: {
    eras: [tr('起伏', 'Swell'), tr('模仿', 'Mimicry'), tr('对称体', 'Symmetriads'), tr('对话', 'Dialogue'), tr('凝视', 'Gaze')],
    first: tr('元年。海第一次动了一下。它还不知道自己是一片海。', 'Year One. The ocean moved for the first time. It doesn\'t know yet that it is an ocean.'),
    up: [
      tr('海开始模仿它看到的东西：浮起一块形状，又慢慢化开。', 'The ocean began imitating what it sees: raising a shape, then slowly dissolving it.'),
      tr('第一座对称体从海面升起，左右完全一样，里面空无一物。', 'The first symmetriad rose from the surface, perfectly mirrored, empty inside.'),
      tr('海开始回应。我迈一步，海面上就起一道同样长度的波纹。', 'The ocean began to answer. For every step I take, a ripple of the same length crosses its surface.'),
      tr('整片海安静下来，所有的起伏都朝向我。它在看我，就像我一直在看它。', 'The whole ocean went still, every swell turned toward me. It\'s looking at me, the way I\'ve always looked at it.'),
    ],
    name: tr('海没有给我起名字。它只是在我经过的地方，造了一个和我一样橙的形状。', 'The ocean didn\'t name me. It just made an orange shape, exactly like me, wherever I passed.'),
    words: [tr('海的念头', 'Thoughts'), tr('对称体', 'symmetriads'), tr('拟态体', 'mimoids')],
    s: {
      found: m => tr(`海在深处浮出一个词：${m}。它反复念这个词，像是在念自己的名字。`, `A word surfaced from the depths: ${m}. The ocean kept repeating it, like its own name.`),
      dynasty: (a, b) => tr(`海的念头换了一种口音：前面是 ${a}，后面是 ${b}。浪还是那些浪。`, `The ocean's thoughts changed accent: ${a} before, ${b} after. The waves are the same waves.`),
      commit: (msg, k) => tr(`海把一句话凝固在海面上，这是它留下的第 ${k} 句：「${msg}」。`, `The ocean froze a sentence onto its surface, the ${nth(k)} it has chosen to keep: "${msg}".`),
      plague: e => tr(`海做了一个它自己也看不懂的梦。醒来的时候，海面上浮着：「${e}」。`, `The ocean had a dream it couldn't understand. When it woke, floating on the surface was: "${e}".`),
      cure: (e, y) => tr(`海花了 ${y} 年才弄懂「${e}」那个梦。弄懂以后，它平静了很多。`, `It took the ocean ${y} years to understand the "${e}" dream. Once it did, it grew much calmer.`),
      mystery: e => tr(`「${e}」那个梦海一直没弄懂。那片海域到现在还在翻涌。`, `The ocean never understood the "${e}" dream. That stretch of water still churns.`),
      rebuild: (f, n) => tr(`海一遍又一遍地造同一个形状，它叫它「${f}」。${n} 次，没有一次让它满意。`, `The ocean builds the same shape over and over. It calls it "${f}". ${n} times, and never once satisfied.`),
      caravan: p => tr(`一些不属于海的东西漂了进来：${p}。海把它们包起来，慢慢学会了它们的样子。`, `Things that don't belong to the ocean drifted in: ${p}. It wrapped them up and slowly learned their shapes.`),
      nay: q => tr(`海听见一个声音：「${q}」。它把刚造好的对称体整个吞了回去。`, `The ocean heard a voice: "${q}". It swallowed its newest symmetriad whole.`),
    },
  },
  crystal: {
    eras: [tr('成核', 'Nucleation'), tr('生长', 'Growth'), tr('晶簇', 'Clusters'), tr('共振', 'Resonance'), tr('透明', 'Clarity')],
    first: tr('元年。过饱和的纸面上出现了第一批晶核。', 'Year One. The first seeds of crystal appear on the supersaturated paper.'),
    up: [
      tr('晶核开始生长，沿着同一个角度，一层一层往外排。', 'The seeds began to grow, stacking outward layer by layer at the same angle.'),
      tr('晶体长成了晶簇。每一簇都朝着光长，虽然这里的光没有方向。', 'The crystals grew into clusters, all reaching toward the light, though light has no direction here.'),
      tr('晶簇之间开始共振。我走过的时候，整片晶林发出一个很低的音。', 'The clusters began to resonate. When I walk past, the whole crystal forest hums one low note.'),
      tr('晶体透明了。从里面看出去，它们第一次看见了我。', 'The crystals turned clear. Looking out from inside, they saw me for the first time.'),
    ],
    name: tr('晶体按我的样子长出了一块杂质。它们管它叫「橙色缺陷」。', 'The crystals grew an impurity in my shape. They call it "the orange defect".'),
    words: [tr('晶核', 'Seeds'), tr('晶簇', 'clusters'), tr('共振腔', 'resonators')],
    s: {
      found: m => tr(`晶体选定了一种晶型：${m}。之后长出来的每一层都照着它排。`, `The crystals settled on a lattice: ${m}. Every layer since has followed it.`),
      dynasty: (a, b) => tr(`晶型变了：${a} 型晶体的外面，开始长 ${b} 型。断面上能看见清楚的分界线。`, `The lattice changed: ${b} started growing over ${a}. You can see the boundary clearly in cross-section.`),
      commit: (msg, k) => tr(`第 ${k} 层晶面长好了。晶面上的纹路读出来是：「${msg}」。`, `The ${nth(k)} crystal face finished growing. The pattern on it reads: "${msg}".`),
      plague: e => tr(`晶格里出现了位错，一整片晶体都长歪了。位错的形状是：「${e}」。`, `A dislocation appeared in the lattice, and a whole region grew crooked. It's shaped like "${e}".`),
      cure: (e, y) => tr(`过了 ${y} 年，一次缓慢的退火把「${e}」位错消掉了。`, `After ${y} years, a slow anneal removed the "${e}" dislocation.`),
      mystery: e => tr(`「${e}」位错一直没有消掉。后来长出来的晶体都绕着它弯了一下。`, `The "${e}" dislocation never went away. Every crystal grown since bends around it.`),
      rebuild: (f, n) => tr(`叫「${f}」的那一簇溶了又长、长了又溶，一共 ${n} 次，每次都更整齐一点。`, `The cluster called "${f}" dissolved and regrew ${n} times, a little neater each time.`),
      caravan: p => tr(`溶液里混进了新的离子：${p}。晶体把它们也排了进去。`, `New ions got into the solution: ${p}. The crystals lined them up too.`),
      nay: q => tr(`一阵震动传过来，带着一句话：「${q}」。最新长的那一层整片裂开，从头再长。`, `A tremor came through, carrying a sentence: "${q}". The newest layer cracked off whole, and growth started again.`),
    },
  },
  pcb: {
    eras: [tr('上电', 'Power-on'), tr('时钟', 'Clock'), tr('总线', 'Bus'), tr('调度', 'Scheduling'), tr('自举', 'Bootstrap')],
    first: tr('元年。电源接通了。第一批电子沿着走线跑了起来。', 'Year One. Power on. The first electrons start running along the traces.'),
    up: [
      tr('时钟开始跳动。从这一刻起，每件事都有了先后。', 'The clock started ticking. From now on, everything happens in order.'),
      tr('总线接通了。信号开始在芯片之间来回搬东西。', 'The bus came up. Signals began carrying things back and forth between chips.'),
      tr('一个调度器出现了，开始决定谁先跑、谁等着。它也开始记录一个查不出来源的中断——那是我。', 'A scheduler appeared, deciding who runs first and who waits. It also started logging an interrupt with no known source. That\'s me.'),
      tr('板子第一次读取了自己的固件，读到了关于我的那一段。它醒了。', 'The board read its own firmware for the first time, and got to the part about me. It\'s awake.'),
    ],
    name: tr('它们把我登记成「IRQ ∞」：一个优先级最高、却查不到来源的中断。', 'They registered me as "IRQ ∞": the highest-priority interrupt, with no traceable source.'),
    words: [tr('进程', 'Processes'), tr('节点', 'nodes'), tr('中断向量', 'vectors')],
    s: {
      found: m => tr(`板子刷入了第一版固件：${m}。`, `The board was flashed with its first firmware: ${m}.`),
      dynasty: (a, b) => tr(`固件刷写：${a} → ${b}。重启以后，所有进程都换了一种说话方式。`, `Firmware update: ${a} → ${b}. After the reboot, every process talks a little differently.`),
      commit: (msg, k) => tr(`第 ${k} 次写入闪存：「${msg}」。断电也不会丢了。`, `Flash write #${k}: "${msg}". It survives power-off now.`),
      plague: e => tr(`一处短路让半块板子反复重启，日志里全是：「${e}」。`, `A short circuit kept half the board rebooting. The log is full of: "${e}".`),
      cure: (e, y) => tr(`「${e}」持续了 ${y} 个周期，终于有人打上了补丁。`, `"${e}" lasted ${y} cycles until someone finally patched it.`),
      mystery: e => tr(`「${e}」一直没修好。那一块区域被标成了 DO NOT USE。`, `"${e}" was never fixed. That region is marked DO NOT USE.`),
      rebuild: (f, n) => tr(`「${f}」这个模块被重写了 ${n} 次，每次重写它都更小一点。`, `The "${f}" module has been rewritten ${n} times, a little smaller each time.`),
      caravan: p => tr(`有新的外设插了进来：${p}。驱动装好以后，板子多了几只手。`, `New peripherals plugged in: ${p}. Once the drivers loaded, the board had a few more hands.`),
      nay: q => tr(`一个不可屏蔽中断：「${q}」。所有进程回滚到上一个检查点。`, `A non-maskable interrupt: "${q}". Every process rolled back to the last checkpoint.`),
    },
  },
  ink: {
    eras: [tr('落墨', 'First Ink'), tr('点染', 'Washes'), tr('成景', 'Landscape'), tr('题跋', 'Inscriptions'), tr('出画', 'Stepping Out')],
    first: tr('元年。画纸上落下了第一笔。一个很小的人从墨点里站了起来。', 'Year One. The first brushstroke touched the paper. A tiny figure stood up out of the ink.'),
    up: [
      tr('画里的小人多了起来，有的撑船，有的挑担，每个都只有几笔。', 'More figures appeared: some poling boats, some carrying loads, each just a few strokes.'),
      tr('一座座亭台楼阁被画了出来，小人们搬了进去。远处的山淡得像雾。', 'Pavilions and towers were painted in, and the figures moved in. The distant hills are as faint as mist.'),
      tr('小人们开始在画的空白处题字。它们发现，字写在哪里，哪里就有了意思。', 'The figures began writing in the blank spaces. They found that wherever words are written, meaning appears.'),
      tr('一个撑船的小人把船划到画纸的边缘，一脚迈了出来。它回头看我，好像早就知道我在画外。', 'A boatman poled right to the edge of the paper and stepped out. It looked back at me as if it always knew I was outside the painting.'),
    ],
    name: tr('画里的小人以为我是画家的手。每次我经过，它们都停下来，等着被添上几笔。', 'The figures think I\'m the painter\'s hand. When I pass, they stop and wait to be given a few more strokes.'),
    words: [tr('画中人', 'Figures'), tr('楼阁', 'pavilions'), tr('题跋', 'inscriptions')],
    s: {
      found: m => tr(`画卷的角上有一方印：${m}。小人们说，这是画这幅画的人。`, `There's a seal in the corner of the scroll: ${m}. The figures say that's who painted it.`),
      dynasty: (a, b) => tr(`画到一半换了一个画师：前半卷的印是 ${a}，后半卷是 ${b}。笔法不一样，小人们一眼就看得出来。`, `The painter changed halfway: the first half is sealed ${a}, the second ${b}. The brushwork differs, and the figures can tell at a glance.`),
      commit: (msg, k) => tr(`卷上添了第 ${k} 段题跋：「${msg}」。`, `The ${nth(k)} inscription was added to the scroll: "${msg}".`),
      plague: e => tr(`一笔败笔落在画上，墨晕开了一大片。晕开的地方隐约能认出：「${e}」。`, `A bad stroke fell on the painting, and the ink bled wide. In the blot you can almost read: "${e}".`),
      cure: (e, y) => tr(`过了 ${y} 年，画家回来补了几笔，「${e}」那块墨渍变成了一块山石。`, `After ${y} years, the painter came back and added a few strokes. The "${e}" blot became a rock.`),
      mystery: e => tr(`「${e}」那块墨渍一直没补。小人们在旁边盖了一座亭子，说那是画里最深的地方。`, `The "${e}" blot was never fixed. The figures built a pavilion beside it and say it's the deepest place in the painting.`),
      rebuild: (f, n) => tr(`「${f}」那座楼画了又洗、洗了又画，一共 ${n} 遍。那里的纸都起毛了。`, `The "${f}" tower was painted and washed out ${n} times. The paper is going furry there.`),
      caravan: p => tr(`画外飞进来几样东西，被随手画进了画里：${p}。`, `A few things flew in from outside and got painted in on the spot: ${p}.`),
      nay: q => tr(`画外传来一句：「${q}」。一盆清水泼下来，刚画好的那一片洗得干干净净。`, `A voice from outside: "${q}". A basin of clean water came down and washed the newest part blank.`),
    },
  },
  blueprint: {
    eras: [tr('草图', 'Sketch'), tr('定稿', 'Final Draft'), tr('施工', 'Construction'), tr('验收', 'Inspection'), tr('建成', 'Built')],
    first: tr('元年。图纸上画出了第一根线。一个尺寸标注跟着出现，量了量它。', 'Year One. The first line appears on the drawing. A dimension label appears too, and measures it.'),
    up: [
      tr('草图定稿了。每个零件都有了编号，每个编号都有了位置。', 'The sketch is final. Every part has a number, every number has a place.'),
      tr('施工开始了。标注们爬到零件上，一个一个核对尺寸。', 'Construction started. The dimension labels climb onto the parts and check each one.'),
      tr('验收员来了。它们在每张图的右下角签字，也在我经过的地方画了一个问号。', 'The inspectors arrived. They sign the bottom-right corner of every sheet, and they drew a question mark where I walked.'),
      tr('图纸上的东西第一次立了起来，有了高度。验收员把我从「画错的线」那一栏划掉，改填进了「已建成」。', 'For the first time, something on the drawing stood up and had height. The inspectors moved me from the "drafting errors" column to "as built".'),
    ],
    name: tr('它们给我标了一个尺寸：「厚度 = ?」，旁边批注：待确认。', 'They dimensioned me: "THICKNESS = ?", with a note beside it: TO BE CONFIRMED.'),
    words: [tr('构件', 'Parts'), tr('图块', 'blocks'), tr('批注', 'notes')],
    s: {
      found: m => tr(`图框里写着设计单位：${m}。`, `The title block names the designer: ${m}.`),
      dynasty: (a, b) => tr(`设计单位变更：${a} → ${b}。所有图纸重新盖章。`, `Change of designer: ${a} → ${b}. Every sheet was re-stamped.`),
      commit: (msg, k) => (r => tr(`图纸升版到 Rev.${r}：「${msg}」。`, `Drawing revised to Rev.${r}: "${msg}".`))(String.fromCharCode(64 + Math.min(26, k))),
      plague: e => tr(`两个构件在图上撞到了一起，碰撞检查报出：「${e}」。`, `Two parts collided on the drawing. The clash check reports: "${e}".`),
      cure: (e, y) => tr(`「${e}」这处碰撞挂了 ${y} 年，终于出了一张变更单把它解决了。`, `The "${e}" clash stayed open for ${y} years before a change order finally resolved it.`),
      mystery: e => tr(`「${e}」一直没解决。那一块被红笔云线圈了起来，旁边写着「待定」。`, `"${e}" was never resolved. That area is clouded in red, marked "TBD".`),
      rebuild: (f, n) => tr(`「${f}」这张详图改了 ${n} 版，图号底下的修改记录已经写不下了。`, `The "${f}" detail has been revised ${n} times; the revision notes no longer fit under the drawing number.`),
      caravan: p => tr(`采购清单里加了几样外购件：${p}。`, `A few bought-in parts were added to the bill of materials: ${p}.`),
      nay: q => tr(`甲方来电：「${q}」。整层重画。`, `A call from the client: "${q}". The whole floor gets redrawn.`),
    },
  },
  slide: {
    eras: [tr('分裂', 'Division'), tr('组织', 'Tissue'), tr('器官', 'Organs'), tr('免疫', 'Immunity'), tr('意识', 'Awareness')],
    first: tr('元年。切片上的第一个细胞分裂成了两个。', 'Year One. The first cell on the slide divides into two.'),
    up: [
      tr('细胞们挤在一起，长成了组织。它们开始分工。', 'The cells packed together into tissue and began dividing up the work.'),
      tr('组织围成了器官，有了里面和外面。一些细胞开始专门往外送东西。', 'Tissues wrapped into organs, with an inside and an outside. Some cells now specialise in sending things out.'),
      tr('免疫系统上线了，开始给每样东西分类：自己的，外来的。我被归进第二类，还单独开了一页。', 'The immune system came online and began sorting everything into self and foreign. I went into the second category, on a page of my own.'),
      tr('一团神经细胞第一次连成了回路。信号绕了一圈，停在了我身上。', 'A cluster of nerve cells closed its first circuit. The signal went round once and stopped on me.'),
    ],
    name: tr('免疫细胞给我贴了一个标签：「外来，太大，吞不下」。', 'Immune cells tagged me: "FOREIGN. TOO LARGE TO ENGULF."'),
    words: [tr('细胞', 'Cells'), tr('组织', 'tissues'), tr('抗体', 'antibodies')],
    s: {
      found: m => tr(`细胞核里读出了第一段基因：${m}。之后的每一次分裂都照着它抄。`, `The first gene read out of the nucleus: ${m}. Every division since has copied it.`),
      dynasty: (a, b) => tr(`一次突变：${a} 基因被 ${b} 取代。新长出来的细胞形状不太一样了。`, `A mutation: ${a} was replaced by ${b}. New cells come out a slightly different shape.`),
      commit: (msg, k) => tr(`第 ${k} 段序列写进了基因组：「${msg}」。之后每个细胞都会带着它。`, `The ${nth(k)} sequence was written into the genome: "${msg}". Every cell will carry it from now on.`),
      plague: e => tr(`一场感染在组织里扩散，被感染的细胞都在重复同一个信号：「${e}」。`, `An infection spread through the tissue. Every infected cell repeats the same signal: "${e}".`),
      cure: (e, y) => tr(`感染持续了 ${y} 代，细胞们终于造出了「${e}」的抗体。`, `The infection lasted ${y} generations before the cells produced an antibody to "${e}".`),
      mystery: e => tr(`「${e}」一直没被清除。周围长出一圈瘢痕，把它包在了里面。`, `"${e}" was never cleared. A ring of scar tissue grew around it and sealed it in.`),
      rebuild: (f, n) => tr(`叫「${f}」的那个器官更新了 ${n} 次，每次都有一批细胞退下、一批新的补上。`, `The organ called "${f}" has renewed itself ${n} times, one batch of cells retiring, another taking its place.`),
      caravan: p => tr(`一些共生菌搬了进来：${p}。它们住下以后，组织好像更能干了。`, `Some symbiotic bacteria moved in: ${p}. Since they settled, the tissue seems more capable.`),
      nay: q => tr(`一个信号从外面传进来：「${q}」。最新长出来的那一片细胞集体凋亡了。`, `A signal came from outside: "${q}". The newest patch of cells underwent apoptosis together.`),
    },
  },
};
const CIV = CIVS[G.theme] || CIVS.earth;
