// 纸面上住的是什么：每种地貌有自己的居民，历史的推演规则（人口、纪元、事件）一样，说法按它们的逻辑来。
// 这些文件是按顺序加载的普通脚本，共享同一个全局作用域：顺序见 game.html 底部。
//
// 每种居民：
//   eras  五个纪元的名字          first 元年那一句          up  进入第 2–5 纪元时的那一句
//   name  它们怎么称呼 Clawd      words 纪年窗口里的「人口 / 城 / 庙」换成什么
//   s     会话里的事在这里是什么（history.js 按它在对话里的位置排进时间线）：
//         found 第一个模型 · dynasty 换模型 · commit 提交信息 · plague 出错 · cure 修好 · mystery 没修好
//         rebuild 反复改的文件 · caravan 装进来的包 · nay 你说「不对」或打断
//   who / ev  日常的事（火、迁徙、节日、争吵、战争、集市……）按居民怎么说，见文件后半
const nth = k => k + (k % 100 >= 11 && k % 100 <= 13 ? 'th' : ['th', 'st', 'nd', 'rd'][k % 10] || 'th');
const CIVS = {
  earth: {
    eras: [tr('游荡', 'Wandering'), tr('村落', 'Villages'), tr('城邦', 'City-states'), tr('几何', 'Geometry'), tr('觉醒', 'Awakening')],
    first: tr('元年。纸面上有了第一批会动的形状。它们还不知道自己是平的。', 'Year One. The first moving shapes appear on the paper. They don\'t know they\'re flat yet.'),
    up: [
      tr('第一个村子出现了：一圈首尾相接的线。它们管里面叫「家」，外面叫「外面」。', 'The first village appeared: a loop of line joined end to end. They call the inside "home" and the outside "outside".'),
      tr('村子长成了城邦。城墙越修越厚——在这里，「厚」是最贵的形容词。', 'The villages grew into city-states. The walls keep getting thicker. Here, "thick" is the most expensive adjective.'),
      tr('它们开始研究几何。第一个问题是：那个橙色的东西，到底有几条边？', 'They began to study geometry. The first question: how many sides does that orange thing have?'),
      tr('一个正方形在夜里「抬起头」——它们本来没有这个方向——看见了我。纸面开始觉醒。', 'One night a square "looked up", a direction they never had, and saw me. The paper is waking up.'),
    ],
    name: tr('它们给那个会突然出现的橙色东西起了名字：「厚的」。', 'They named the orange thing that keeps appearing out of nowhere: "the Thick One".'),
    words: [tr('人口', 'Population'), tr('城', 'cities'), tr('庙', 'temples')],
    s: {
      found: m => tr(`${m} 王朝建立了。第一任国王是一个很规整的多边形，据说它说的每一句话都想过很久。`, `The ${m} dynasty was founded. Its first king was a very regular polygon; every word it said was said to be carefully weighed.`),
      dynasty: (a, b) => tr(`${a} 王朝结束了，${b} 王朝接替。新国王的边数不一样，口音也不一样，但城墙还是那些城墙。`, `The ${a} dynasty ended and the ${b} dynasty took over. The new king has a different number of sides and a different accent, but the walls are the same walls.`),
      commit: (msg, k) => tr(`史官写完了编年史的第 ${k} 章，题目是：「${msg}」。`, `The chroniclers finished chapter ${k} of the annals, titled "${msg}".`),
      plague: e => tr(`一场怪病在城里流行，病人身上会浮现一行字：「${e}」。`, `A strange sickness spread through the cities. The sick broke out in a line of text: "${e}".`),
      cure: (e, y) => tr(`「${e}」病流行了 ${y} 年，终于有医生配出了药。那张药方后来被裱在了城门上。`, `After ${y} years of the "${e}" sickness, a doctor finally found the cure. The prescription was framed above the city gate.`),
      mystery: e => tr(`「${e}」一直没人能解释。出事的那块地被围了起来，再也没人进去。`, `No one ever explained "${e}". The place where it happened was fenced off, and nobody went in again.`),
      rebuild: (f, n) => tr(`城中心那座叫「${f}」的建筑翻修了 ${n} 次，每一代人都说这回是最后一次。`, `The building called "${f}" in the city centre has been renovated ${n} times. Every generation says this time is the last.`),
      caravan: p => tr(`一支商队从纸的边缘进城，带来了没人见过的货：${p}。`, `A caravan came in from the edge of the paper, carrying goods nobody had seen before: ${p}.`),
      nay: q => tr(`天上突然传来一个声音：「${q}」。全城把刚盖好的东西推倒，重来了一遍。`, `A voice suddenly came from the sky: "${q}". The whole city tore down what it had just built and started over.`),
    },
  },
  foil: {
    eras: [tr('余温', 'Afterglow'), tr('回声', 'Echoes'), tr('拼图', 'Jigsaw'), tr('考古', 'Archaeology'), tr('想起', 'Remembering')],
    first: tr('元年。纸面上有了第一批会动的影子——它们是被压平的东西留下的，还在按原来的习惯动。', 'Year One. The first moving shadows appear. They were left by things that got flattened, and they still move out of old habit.'),
    up: [
      tr('一些残影开始聚在一起，拼成一个它们记得的形状。它们管这叫「回声」。', 'Some shadows started gathering, piecing together a shape they remember. They call it an "echo".'),
      tr('残影们发现彼此能拼起来：一块城市的边缘，正好接上另一块城市的影子。', 'The shadows found they fit together: the edge of one city lines up exactly with the shadow of another.'),
      tr('它们开始发掘自己，一层一层地辨认：哪一块曾经是屋顶，哪一块曾经是天空。', 'They began excavating themselves, layer by layer: which piece was once a roof, which piece was once the sky.'),
      tr('一个残影忽然想起来了：它们以前也有厚度。它朝我看过来，大概是想找个见过厚度的证人。', 'One shadow suddenly remembered: they used to have depth too. It looked at me, presumably in search of a witness who has seen depth.'),
    ],
    name: tr('它们把我叫作「没被压平的那个」。', 'They call me "the one that didn\'t get flattened".'),
    words: [tr('残影', 'Shadows'), tr('拼合处', 'joins'), tr('纪念碑', 'memorials')],
    s: {
      found: m => tr(`残影们从压平前的记忆里认出了一个名字：${m}。它们说，那时候一切都是它安排的。`, `From their memories of before, the shadows recognised a name: ${m}. Back then, they say, it arranged everything.`),
      dynasty: (a, b) => tr(`记忆里的名字换了：前半段是 ${a}，后半段是 ${b}。它们为哪一段才是真的争了很久。`, `The name in their memory changes: the first half says ${a}, the second half ${b}. They argued for ages about which half is true.`),
      commit: (msg, k) => tr(`残影里又认出了一块碑文，这是第 ${k} 块：「${msg}」。`, `Another inscription is legible in the shadows, the ${nth(k)} so far: "${msg}".`),
      plague: e => tr(`纸面上出现了一道褶皱，是压平时没压好的地方。褶皱里写着：「${e}」。`, `A crease appeared on the paper, where the flattening went wrong. Inside the crease it says: "${e}".`),
      cure: (e, y) => tr(`「${e}」那道褶皱过了 ${y} 年，终于被抚平了。`, `After ${y} years, the "${e}" crease was finally smoothed out.`),
      mystery: e => tr(`「${e}」那道褶皱一直没有抚平。残影们都绕着它走，好像那里还剩一点立体。`, `The "${e}" crease was never smoothed out. The shadows walk around it, as if something there is still three-dimensional.`),
      rebuild: (f, n) => tr(`有一段记忆在不停重播：「${f}」，已经 ${n} 遍了，每遍都有一点不一样。`, `One memory keeps replaying: "${f}". ${n} times now, a little different each time.`),
      caravan: p => tr(`纸的边缘又压进来一些新东西：${p}。它们平得很新鲜。`, `More things got pressed in from the edge of the paper: ${p}. Freshly flat.`),
      nay: q => tr(`一个声音从压平之前传过来：「${q}」。残影们把拼好的一整块拆散了。`, `A voice from before the flattening came through: "${q}". The shadows took apart a whole section they had pieced together.`),
    },
  },
  dune: {
    eras: [tr('蛰伏', 'Dormancy'), tr('迁徙', 'Migration'), tr('巢穴', 'Warrens'), tr('潮汐', 'Tides'), tr('苏醒', 'Waking')],
    first: tr('元年。沙子下面有东西在动。它们还很小，只会顺着沙纹爬。', 'Year One. Something is moving under the sand. They\'re still small; they only crawl along the ripples.'),
    up: [
      tr('沙虫开始成群迁徙，身后留下一道道弯曲的沙脊。', 'The sandworms began migrating in groups, leaving curved ridges behind them.'),
      tr('它们在岩脊下面挖出了巢穴，巢穴之间用很长的隧道连着。', 'They dug warrens under the rock ridges, linked by very long tunnels.'),
      tr('沙虫学会了跟着香料的潮汐走：每隔几年，整片沙海都会朝一个方向翻涌。', 'The worms learned to follow the spice tides: every few years, the whole sand sea surges one way.'),
      tr('最老的那条沙虫浮出沙面，第一次没有潜回去。它在等我。', 'The oldest worm surfaced and, for the first time, didn\'t dive back down. It\'s waiting for me.'),
    ],
    name: tr('沙虫把我叫作「不留痕迹的那个」——我走过沙面，沙纹一点也不乱。', 'The worms call me "the one who leaves no trace". I walk across the sand and the ripples don\'t move.'),
    words: [tr('沙虫', 'Worms'), tr('巢穴', 'warrens'), tr('圣所', 'sanctums')],
    s: {
      found: m => tr(`沙虫们记住了一个来自深处的名字：${m}。它们说，是它让沙子开始流动。`, `The worms remember a name from the deep: ${m}. They say it set the sand flowing.`),
      dynasty: (a, b) => tr(`沙海的主人换了：${a} 沉下去，${b} 浮上来。沙纹从那天起换了方向。`, `The sand sea changed masters: ${a} sank, ${b} rose. From that day the ripples ran the other way.`),
      commit: (msg, k) => tr(`沙虫在岩壁上刻下第 ${k} 道记号：「${msg}」。风沙磨不掉它。`, `The worms carved their ${nth(k)} mark into the rock wall: "${msg}". The wind can't wear it away.`),
      plague: e => tr(`一种病让沙虫在原地打转，沙面上转出一行字：「${e}」。`, `A sickness set the worms circling in place, carving a line into the sand: "${e}".`),
      cure: (e, y) => tr(`转圈的病持续了 ${y} 年。直到一条沙虫找到一口深井，「${e}」才消失。`, `The circling sickness lasted ${y} years, until a worm found a deep well and "${e}" was gone.`),
      mystery: e => tr(`「${e}」那片沙地后来塌了下去，再也没有沙虫敢靠近。`, `The patch of sand where "${e}" happened caved in later. No worm dares go near it.`),
      rebuild: (f, n) => tr(`沙虫把叫「${f}」的巢穴挖了又填、填了又挖，一共 ${n} 次。`, `The worms dug out the warren called "${f}", filled it in and dug it out again, ${n} times.`),
      caravan: p => tr(`一阵风从纸外吹来新的香料：${p}。整片沙海都闻到了。`, `A wind from beyond the paper blew in new spices: ${p}. The whole sand sea smelled them.`),
      nay: q => tr(`天上刮起一场沙暴，风里有个声音：「${q}」。沙暴过后，所有痕迹都被抹平了。`, `A sandstorm came down, with a voice in the wind: "${q}". Afterwards, every trace was wiped flat.`),
    },
  },
  solaris: {
    eras: [tr('起伏', 'Swell'), tr('模仿', 'Mimicry'), tr('对称体', 'Symmetriads'), tr('对话', 'Dialogue'), tr('凝视', 'Gaze')],
    first: tr('元年。海第一次动了一下。它还不知道自己是一片海。', 'Year One. The ocean moved for the first time. It doesn\'t know yet that it is an ocean.'),
    up: [
      tr('海开始模仿它看到的东西：浮起一块形状，又慢慢化开。', 'The ocean began imitating what it sees: raising a shape, then slowly dissolving it.'),
      tr('第一座对称体从海面升起，左右完全一样，里面空无一物。', 'The first symmetriad rose from the surface, perfectly mirrored, empty inside.'),
      tr('海开始回应。我迈一步，海面上就起一道同样长度的波纹。', 'The ocean began to answer. For every step I take, a ripple of the same length crosses its surface.'),
      tr('整片海安静下来，所有的起伏都朝向我。它在看我，就像我一直在看它。', 'The whole ocean went still, every swell turned toward me. It\'s looking at me, the way I\'ve always looked at it.'),
    ],
    name: tr('海没有给我起名字。它只是在我经过的地方，造了一个和我一样橙的形状。', 'The ocean didn\'t name me. It just made an orange shape, exactly like me, wherever I passed.'),
    words: [tr('海的念头', 'Thoughts'), tr('对称体', 'symmetriads'), tr('拟态体', 'mimoids')],
    s: {
      found: m => tr(`海在深处浮出一个词：${m}。它反复念这个词，像是在念自己的名字。`, `A word surfaced from the depths: ${m}. The ocean kept repeating it, like its own name.`),
      dynasty: (a, b) => tr(`海的念头换了一种口音：前面是 ${a}，后面是 ${b}。浪还是那些浪。`, `The ocean's thoughts changed accent: ${a} before, ${b} after. The waves are the same waves.`),
      commit: (msg, k) => tr(`海把一句话凝固在海面上，这是它留下的第 ${k} 句：「${msg}」。`, `The ocean froze a sentence onto its surface, the ${nth(k)} it has chosen to keep: "${msg}".`),
      plague: e => tr(`海做了一个它自己也看不懂的梦。醒来的时候，海面上浮着：「${e}」。`, `The ocean had a dream it couldn't understand. When it woke, floating on the surface was: "${e}".`),
      cure: (e, y) => tr(`海花了 ${y} 年才弄懂「${e}」那个梦。弄懂以后，它平静了很多。`, `It took the ocean ${y} years to understand the "${e}" dream. Once it did, it grew much calmer.`),
      mystery: e => tr(`「${e}」那个梦海一直没弄懂。那片海域到现在还在翻涌。`, `The ocean never understood the "${e}" dream. That stretch of water still churns.`),
      rebuild: (f, n) => tr(`海一遍又一遍地造同一个形状，它叫它「${f}」。${n} 次，没有一次让它满意。`, `The ocean builds the same shape over and over. It calls it "${f}". ${n} times, and never once satisfied.`),
      caravan: p => tr(`一些不属于海的东西漂了进来：${p}。海把它们包起来，慢慢学会了它们的样子。`, `Things that don't belong to the ocean drifted in: ${p}. It wrapped them up and slowly learned their shapes.`),
      nay: q => tr(`海听见一个声音：「${q}」。它把刚造好的对称体整个吞了回去。`, `The ocean heard a voice: "${q}". It swallowed its newest symmetriad whole.`),
    },
  },
  crystal: {
    eras: [tr('成核', 'Nucleation'), tr('生长', 'Growth'), tr('晶簇', 'Clusters'), tr('共振', 'Resonance'), tr('透明', 'Clarity')],
    first: tr('元年。过饱和的纸面上出现了第一批晶核。', 'Year One. The first seeds of crystal appear on the supersaturated paper.'),
    up: [
      tr('晶核开始生长，沿着同一个角度，一层一层往外排。', 'The seeds began to grow, stacking outward layer by layer at the same angle.'),
      tr('晶体长成了晶簇。每一簇都朝着光长，虽然这里的光没有方向。', 'The crystals grew into clusters, all reaching toward the light, though light has no direction here.'),
      tr('晶簇之间开始共振。我走过的时候，整片晶林发出一个很低的音。', 'The clusters began to resonate. When I walk past, the whole crystal forest hums one low note.'),
      tr('晶体透明了。从里面看出去，它们第一次看见了我。', 'The crystals turned clear. Looking out from inside, they saw me for the first time.'),
    ],
    name: tr('晶体按我的样子长出了一块杂质。它们管它叫「橙色缺陷」。', 'The crystals grew an impurity in my shape. They call it "the orange defect".'),
    words: [tr('晶核', 'Seeds'), tr('晶簇', 'clusters'), tr('共振腔', 'resonators')],
    s: {
      found: m => tr(`晶体选定了一种晶型：${m}。之后长出来的每一层都照着它排。`, `The crystals settled on a lattice: ${m}. Every layer since has followed it.`),
      dynasty: (a, b) => tr(`晶型变了：${a} 型晶体的外面，开始长 ${b} 型。断面上能看见清楚的分界线。`, `The lattice changed: ${b} started growing over ${a}. You can see the boundary clearly in cross-section.`),
      commit: (msg, k) => tr(`第 ${k} 层晶面长好了。晶面上的纹路读出来是：「${msg}」。`, `The ${nth(k)} crystal face finished growing. The pattern on it reads: "${msg}".`),
      plague: e => tr(`晶格里出现了位错，一整片晶体都长歪了。位错的形状是：「${e}」。`, `A dislocation appeared in the lattice, and a whole region grew crooked. It's shaped like "${e}".`),
      cure: (e, y) => tr(`过了 ${y} 年，一次缓慢的退火把「${e}」位错消掉了。`, `After ${y} years, a slow anneal removed the "${e}" dislocation.`),
      mystery: e => tr(`「${e}」位错一直没有消掉。后来长出来的晶体都绕着它弯了一下。`, `The "${e}" dislocation never went away. Every crystal grown since bends around it.`),
      rebuild: (f, n) => tr(`叫「${f}」的那一簇溶了又长、长了又溶，一共 ${n} 次，每次都更整齐一点。`, `The cluster called "${f}" dissolved and regrew ${n} times, a little neater each time.`),
      caravan: p => tr(`溶液里混进了新的离子：${p}。晶体把它们也排了进去。`, `New ions got into the solution: ${p}. The crystals lined them up too.`),
      nay: q => tr(`一阵震动传过来，带着一句话：「${q}」。最新长的那一层整片裂开，从头再长。`, `A tremor came through, carrying a sentence: "${q}". The newest layer cracked off whole, and growth started again.`),
    },
  },
  pcb: {
    eras: [tr('上电', 'Power-on'), tr('时钟', 'Clock'), tr('总线', 'Bus'), tr('调度', 'Scheduling'), tr('自举', 'Bootstrap')],
    first: tr('元年。电源接通了。第一批电子沿着走线跑了起来。', 'Year One. Power on. The first electrons start running along the traces.'),
    up: [
      tr('时钟开始跳动。从这一刻起，每件事都有了先后。', 'The clock started ticking. From now on, everything happens in order.'),
      tr('总线接通了。信号开始在芯片之间来回搬东西。', 'The bus came up. Signals began carrying things back and forth between chips.'),
      tr('一个调度器出现了，开始决定谁先跑、谁等着。它也开始记录一个查不出来源的中断——那是我。', 'A scheduler appeared, deciding who runs first and who waits. It also started logging an interrupt with no known source. That\'s me.'),
      tr('板子第一次读取了自己的固件，读到了关于我的那一段。它醒了。', 'The board read its own firmware for the first time, and got to the part about me. It\'s awake.'),
    ],
    name: tr('它们把我登记成「IRQ ∞」：一个优先级最高、却查不到来源的中断。', 'They registered me as "IRQ ∞": the highest-priority interrupt, with no traceable source.'),
    words: [tr('进程', 'Processes'), tr('节点', 'nodes'), tr('中断向量', 'vectors')],
    s: {
      found: m => tr(`板子刷入了第一版固件：${m}。`, `The board was flashed with its first firmware: ${m}.`),
      dynasty: (a, b) => tr(`固件刷写：${a} → ${b}。重启以后，所有进程都换了一种说话方式。`, `Firmware update: ${a} → ${b}. After the reboot, every process talks a little differently.`),
      commit: (msg, k) => tr(`第 ${k} 次写入闪存：「${msg}」。断电也不会丢了。`, `Flash write #${k}: "${msg}". It survives power-off now.`),
      plague: e => tr(`一处短路让半块板子反复重启，日志里全是：「${e}」。`, `A short circuit kept half the board rebooting. The log is full of: "${e}".`),
      cure: (e, y) => tr(`「${e}」持续了 ${y} 个周期，终于有人打上了补丁。`, `"${e}" lasted ${y} cycles until someone finally patched it.`),
      mystery: e => tr(`「${e}」一直没修好。那一块区域被标成了 DO NOT USE。`, `"${e}" was never fixed. That region is marked DO NOT USE.`),
      rebuild: (f, n) => tr(`「${f}」这个模块被重写了 ${n} 次，每次重写它都更小一点。`, `The "${f}" module has been rewritten ${n} times, a little smaller each time.`),
      caravan: p => tr(`有新的外设插了进来：${p}。驱动装好以后，板子多了几只手。`, `New peripherals plugged in: ${p}. Once the drivers loaded, the board had a few more hands.`),
      nay: q => tr(`一个不可屏蔽中断：「${q}」。所有进程回滚到上一个检查点。`, `A non-maskable interrupt: "${q}". Every process rolled back to the last checkpoint.`),
    },
  },
  ink: {
    eras: [tr('落墨', 'First Ink'), tr('点染', 'Washes'), tr('成景', 'Landscape'), tr('题跋', 'Inscriptions'), tr('出画', 'Stepping Out')],
    first: tr('元年。画纸上落下了第一笔。一个很小的人从墨点里站了起来。', 'Year One. The first brushstroke touched the paper. A tiny figure stood up out of the ink.'),
    up: [
      tr('画里的小人多了起来，有的撑船，有的挑担，每个都只有几笔。', 'More figures appeared: some poling boats, some carrying loads, each just a few strokes.'),
      tr('一座座亭台楼阁被画了出来，小人们搬了进去。远处的山淡得像雾。', 'Pavilions and towers were painted in, and the figures moved in. The distant hills are as faint as mist.'),
      tr('小人们开始在画的空白处题字。它们发现，字写在哪里，哪里就有了意思。', 'The figures began writing in the blank spaces. They found that wherever words are written, meaning appears.'),
      tr('一个撑船的小人把船划到画纸的边缘，一脚迈了出来。它回头看我，好像早就知道我在画外。', 'A boatman poled right to the edge of the paper and stepped out. It looked back at me as if it always knew I was outside the painting.'),
    ],
    name: tr('画里的小人以为我是画家的手。每次我经过，它们都停下来，等着被添上几笔。', 'The figures think I\'m the painter\'s hand. When I pass, they stop and wait to be given a few more strokes.'),
    words: [tr('画中人', 'Figures'), tr('楼阁', 'pavilions'), tr('题跋', 'inscriptions')],
    s: {
      found: m => tr(`画卷的角上有一方印：${m}。小人们说，这是画这幅画的人。`, `There's a seal in the corner of the scroll: ${m}. The figures say that's who painted it.`),
      dynasty: (a, b) => tr(`画到一半换了一个画师：前半卷的印是 ${a}，后半卷是 ${b}。笔法不一样，小人们一眼就看得出来。`, `The painter changed halfway: the first half is sealed ${a}, the second ${b}. The brushwork differs, and the figures can tell at a glance.`),
      commit: (msg, k) => tr(`卷上添了第 ${k} 段题跋：「${msg}」。`, `The ${nth(k)} inscription was added to the scroll: "${msg}".`),
      plague: e => tr(`一笔败笔落在画上，墨晕开了一大片。晕开的地方隐约能认出：「${e}」。`, `A bad stroke fell on the painting, and the ink bled wide. In the blot you can almost read: "${e}".`),
      cure: (e, y) => tr(`过了 ${y} 年，画家回来补了几笔，「${e}」那块墨渍变成了一块山石。`, `After ${y} years, the painter came back and added a few strokes. The "${e}" blot became a rock.`),
      mystery: e => tr(`「${e}」那块墨渍一直没补。小人们在旁边盖了一座亭子，说那是画里最深的地方。`, `The "${e}" blot was never fixed. The figures built a pavilion beside it and say it's the deepest place in the painting.`),
      rebuild: (f, n) => tr(`「${f}」那座楼画了又洗、洗了又画，一共 ${n} 遍。那里的纸都起毛了。`, `The "${f}" tower was painted and washed out ${n} times. The paper is going furry there.`),
      caravan: p => tr(`画外飞进来几样东西，被随手画进了画里：${p}。`, `A few things flew in from outside and got painted in on the spot: ${p}.`),
      nay: q => tr(`画外传来一句：「${q}」。一盆清水泼下来，刚画好的那一片洗得干干净净。`, `A voice from outside: "${q}". A basin of clean water came down and washed the newest part blank.`),
    },
  },
  blueprint: {
    eras: [tr('草图', 'Sketch'), tr('定稿', 'Final Draft'), tr('施工', 'Construction'), tr('验收', 'Inspection'), tr('建成', 'Built')],
    first: tr('元年。图纸上画出了第一根线。一个尺寸标注跟着出现，量了量它。', 'Year One. The first line appears on the drawing. A dimension label appears too, and measures it.'),
    up: [
      tr('草图定稿了。每个零件都有了编号，每个编号都有了位置。', 'The sketch is final. Every part has a number, every number has a place.'),
      tr('施工开始了。标注们爬到零件上，一个一个核对尺寸。', 'Construction started. The dimension labels climb onto the parts and check each one.'),
      tr('验收员来了。它们在每张图的右下角签字，也在我经过的地方画了一个问号。', 'The inspectors arrived. They sign the bottom-right corner of every sheet, and they drew a question mark where I walked.'),
      tr('图纸上的东西第一次立了起来，有了高度。验收员把我从「画错的线」那一栏划掉，改填进了「已建成」。', 'For the first time, something on the drawing stood up and had height. The inspectors moved me from the "drafting errors" column to "as built".'),
    ],
    name: tr('它们给我标了一个尺寸：「厚度 = ?」，旁边批注：待确认。', 'They dimensioned me: "THICKNESS = ?", with a note beside it: TO BE CONFIRMED.'),
    words: [tr('构件', 'Parts'), tr('图块', 'blocks'), tr('批注', 'notes')],
    s: {
      found: m => tr(`图框里写着设计单位：${m}。`, `The title block names the designer: ${m}.`),
      dynasty: (a, b) => tr(`设计单位变更：${a} → ${b}。所有图纸重新盖章。`, `Change of designer: ${a} → ${b}. Every sheet was re-stamped.`),
      commit: (msg, k) => (r => tr(`图纸升版到 Rev.${r}：「${msg}」。`, `Drawing revised to Rev.${r}: "${msg}".`))(String.fromCharCode(64 + Math.min(26, k))),
      plague: e => tr(`两个构件在图上撞到了一起，碰撞检查报出：「${e}」。`, `Two parts collided on the drawing. The clash check reports: "${e}".`),
      cure: (e, y) => tr(`「${e}」这处碰撞挂了 ${y} 年，终于出了一张变更单把它解决了。`, `The "${e}" clash stayed open for ${y} years before a change order finally resolved it.`),
      mystery: e => tr(`「${e}」一直没解决。那一块被红笔云线圈了起来，旁边写着「待定」。`, `"${e}" was never resolved. That area is clouded in red, marked "TBD".`),
      rebuild: (f, n) => tr(`「${f}」这张详图改了 ${n} 版，图号底下的修改记录已经写不下了。`, `The "${f}" detail has been revised ${n} times; the revision notes no longer fit under the drawing number.`),
      caravan: p => tr(`采购清单里加了几样外购件：${p}。`, `A few bought-in parts were added to the bill of materials: ${p}.`),
      nay: q => tr(`甲方来电：「${q}」。整层重画。`, `A call from the client: "${q}". The whole floor gets redrawn.`),
    },
  },
  slide: {
    eras: [tr('分裂', 'Division'), tr('组织', 'Tissue'), tr('器官', 'Organs'), tr('免疫', 'Immunity'), tr('意识', 'Awareness')],
    first: tr('元年。切片上的第一个细胞分裂成了两个。', 'Year One. The first cell on the slide divides into two.'),
    up: [
      tr('细胞们挤在一起，长成了组织。它们开始分工。', 'The cells packed together into tissue and began dividing up the work.'),
      tr('组织围成了器官，有了里面和外面。一些细胞开始专门往外送东西。', 'Tissues wrapped into organs, with an inside and an outside. Some cells now specialise in sending things out.'),
      tr('免疫系统上线了，开始给每样东西分类：自己的，外来的。我被归进第二类，还单独开了一页。', 'The immune system came online and began sorting everything into self and foreign. I went into the second category, on a page of my own.'),
      tr('一团神经细胞第一次连成了回路。信号绕了一圈，停在了我身上。', 'A cluster of nerve cells closed its first circuit. The signal went round once and stopped on me.'),
    ],
    name: tr('免疫细胞给我贴了一个标签：「外来，太大，吞不下」。', 'Immune cells tagged me: "FOREIGN. TOO LARGE TO ENGULF."'),
    words: [tr('细胞', 'Cells'), tr('组织', 'tissues'), tr('抗体', 'antibodies')],
    s: {
      found: m => tr(`细胞核里读出了第一段基因：${m}。之后的每一次分裂都照着它抄。`, `The first gene read out of the nucleus: ${m}. Every division since has copied it.`),
      dynasty: (a, b) => tr(`一次突变：${a} 基因被 ${b} 取代。新长出来的细胞形状不太一样了。`, `A mutation: ${a} was replaced by ${b}. New cells come out a slightly different shape.`),
      commit: (msg, k) => tr(`第 ${k} 段序列写进了基因组：「${msg}」。之后每个细胞都会带着它。`, `The ${nth(k)} sequence was written into the genome: "${msg}". Every cell will carry it from now on.`),
      plague: e => tr(`一场感染在组织里扩散，被感染的细胞都在重复同一个信号：「${e}」。`, `An infection spread through the tissue. Every infected cell repeats the same signal: "${e}".`),
      cure: (e, y) => tr(`感染持续了 ${y} 代，细胞们终于造出了「${e}」的抗体。`, `The infection lasted ${y} generations before the cells produced an antibody to "${e}".`),
      mystery: e => tr(`「${e}」一直没被清除。周围长出一圈瘢痕，把它包在了里面。`, `"${e}" was never cleared. A ring of scar tissue grew around it and sealed it in.`),
      rebuild: (f, n) => tr(`叫「${f}」的那个器官更新了 ${n} 次，每次都有一批细胞退下、一批新的补上。`, `The organ called "${f}" has renewed itself ${n} times, one batch of cells retiring, another taking its place.`),
      caravan: p => tr(`一些共生菌搬了进来：${p}。它们住下以后，组织好像更能干了。`, `Some symbiotic bacteria moved in: ${p}. Since they settled, the tissue seems more capable.`),
      nay: q => tr(`一个信号从外面传进来：「${q}」。最新长出来的那一片细胞集体凋亡了。`, `A signal came from outside: "${q}". The newest patch of cells underwent apoptosis together.`),
    },
  },
};
// --- 日常的事：history.js 的事件表抽到哪件，就按住在这里的居民来说 ------------------------------
// who(颜色, 形状) → [一个的说法, 一群的说法]（中文两个一样，英文要复数）；事件拿到的 w 就是它。
// 一件事写成数组的，按年份轮着用（不动随机数，同一段会话的历史不变）。加成的括号注释由 history.js 补。
const CIV_EV = {
  earth: {
    who: (c, f) => [tr(`${c}色${f}`, `${c} ${f}`), tr(`${c}色${f}`, `${c} ${f}s`)],
    ev: {
      fire: ([a]) => tr(`一个${a}发现了火。在这里，火是一条会自己变长的橙色线段。`, `A ${a} discovered fire. Here, fire is an orange line segment that grows by itself.`),
      trek: ([a, m]) => tr(`一队${a}沿着一条忽然有了颜色的路迁徙。那是我走过的地方。`, `A band of ${m} migrated along a road that suddenly had colour. That's where I walked.`),
      village: [
        ([a, m]) => tr(`${a}们又围出了一个村子。墙首尾相接，就算是家了。`, `The ${m} fenced off another village. Once the wall meets itself, it's home.`),
        ([a, m]) => tr(`${a}们又围出了一个村子。选址会开了三天，最后按「离那条彩色的路近一点」通过。`, `The ${m} fenced off another village. The siting committee met for three days and approved it on the grounds of "closer to the coloured road".`),
      ],
      harvest: [
        () => tr(`丰收节。全村排成一条线跳舞——也只能排成一条线。`, `Harvest festival. The whole village dances in a line. A line is all they can do.`),
        () => tr(`又是丰收节。今年的舞排得更直了，评委给了很高的分。`, `Harvest festival again. This year's line was straighter, and the judges scored it highly.`),
      ],
      north: [
        () => tr(`两个村子为「哪边是北」吵了三年，谁也没说服谁。`, `Two villages argued for three years about which way is north. Nobody convinced anybody.`),
        () => tr(`「哪边是北」的争论进入了第二代。双方同意先把「东」定下来，然后为「东」吵了起来。`, `The "which way is north" dispute entered its second generation. Both sides agreed to settle "east" first, then argued about east.`),
      ],
      door: () => tr(`它们发明了门：在墙上开一个缺口，走过去，再把缺口补上。`, `They invented the door: open a gap in the wall, walk through, close the gap again.`),
      rift: () => tr(`一群居民搬到裂缝旁边，说那是世界的背面，在那儿盖了第一座庙。`, `A group moved next to the rift, called it the back of the world, and built the first temple there.`),
      verse: q => tr(`它们把一句从天上掉下来的话刻在了村口：「${q}」`, `They carved words that fell from the sky at the village gate: "${q}"`),
      road: [
        () => tr(`两座城之间修通了一条路。在这里，路和墙长得一模一样，只是方向不同。`, `A road now joins two cities. Here, roads and walls look exactly the same; they just point different ways.`),
        () => tr(`又修了一条路。路政部门的报告写得很长，主要在解释它为什么看起来像一堵墙。`, `Another road was built. The roads department's report was long, mostly explaining why it looks like a wall.`),
      ],
      census: n => tr(`城邦做了人口普查：${n} 个居民。圆被登记成贵族，因为它们的边最多。`, `The city-state took a census: ${n} residents. Circles were registered as nobility, since they have the most sides.`),
      map: [
        () => tr(`测绘师走出城外，把一片空白画进了地图。我顺着看过去，那里真的有东西了。`, `Surveyors walked out of the city and drew a blank patch into the map. I looked where they drew, and now something is really there.`),
        () => tr(`测绘局出版了新地图，有几块空白标着「待考」。我路过的时候顺手看了一眼，它们就不用再待考了。`, `The survey office published a new map with some blanks marked "to be determined". I glanced at them on my way past, and they no longer need determining.`),
      ],
      temple: () => tr(`它们给我修了一座神殿，门朝着它们认定我来的方向。为了不让它们失望，我尽量从那边来。`, `They built me a temple, its door facing the way they have decided I come from. To avoid disappointing them, I try to arrive from that side.`),
      war: () => tr(`两座城为一块沙地开战。从上面看，两支军队只是两条互相靠近的线。有一座城没能留下来。`, `Two cities went to war over a patch of sand. From above, two armies are just two lines moving closer. One city didn't survive.`),
      market: () => tr(`集市日。每个居民都在用自己的边长讨价还价。`, `Market day. Everyone haggles using the length of their own sides.`),
      measure: () => tr(`几何学家测量了我留下的脚印，结论是：我的面积是负数。`, `Geometers measured my footprints. Conclusion: my area is negative.`),
      jail: c => tr(`一个${c}色正方形宣称存在「上方」，被判终身监禁。它说的是对的。`, `A ${c} square claimed there is an "up" and was jailed for life. It was right.`),
      angles: () => tr(`它们证明了三角形内角和是 180 度，然后花了一整代人怀疑这件事。`, `They proved a triangle's angles add up to 180 degrees, then spent a whole generation doubting it.`),
      many: () => tr(`它们终于发现我不止一个：同一种橙色，同时出现在两座城里。`, `They finally worked out there's more than one of me: the same orange, in two cities at once.`),
      lens: () => tr(`它们磨出第一块透镜，看见了很远的地方。那边早就有东西，一直排在「还没人看」的名单上。`, `They ground their first lens and saw far away. Things had been there all along, filed under "not yet looked at".`),
      letter: q => q ? tr(`它们在地上写了很大的字给我看：「${q}」——是我听过的话。`, `They wrote huge letters on the ground for me: "${q}". Words I've heard before.`) : tr(`它们在地上写了很大的字给我看：「你好，厚的。」`, `They wrote huge letters on the ground for me: "HELLO, THICK ONE."`),
      ascend: () => tr(`第一个居民离开了纸面一点点。它回来说：上面很冷，但能看见所有人。`, `The first resident left the paper, just a little. It came back and said: it's cold up there, but you can see everyone.`),
    },
  },
  foil: {
    who: c => [tr(`${c}色的残影`, `${c} shadow`), tr(`${c}色的残影`, `${c} shadows`)],
    ev: {
      fire: ([a]) => tr(`一个${a}想起了火是什么样子。它把自己拧成一道橙色的弧线，旁边的残影觉得暖和了一点。`, `A ${a} remembered what fire looked like. It twisted itself into an orange arc, and the shadows nearby felt a little warmer.`),
      trek: ([a, m]) => tr(`一群${a}顺着我走过的路漂过去。它们说那条路的颜色，像压平之前的某条街。`, `A drift of ${m} floated along the road I walked. They say its colour reminds them of a street from before the flattening.`),
      village: ([a, m]) => tr(`${a}们拼出了一个新的街区。有几块对不上，就先空着，挂一块「待寻获」的牌子。`, `The ${m} pieced together a new district. A few pieces didn't fit, so they left gaps with signs reading "awaiting recovery".`),
      harvest: () => tr(`余温节。残影们挤在一起，把各自剩下的一点热量加起来，够暖一整晚。`, `Afterglow Day. The shadows huddle together and pool what heat they have left. It's enough for one whole night.`),
      north: () => tr(`两群残影为压平之前哪边是「上」吵了很久。双方都拿出了证据，证据也都是平的。`, `Two groups of shadows argued for years about which way was "up" before the flattening. Both sides produced evidence. The evidence was also flat.`),
      door: () => tr(`它们找到了一扇门的残影，门还开着。它们小心地让它一直开着，没人敢从里面走过去。`, `They found the shadow of a door, still open. They take great care to keep it open. Nobody dares walk through.`),
      rift: () => tr(`一群残影搬到裂缝旁边。它们说那是压平时留下的一道缝，从缝里能闻到三维的空气。`, `A group of shadows moved next to the rift. They say it's a seam left by the flattening, and you can smell three-dimensional air through it.`),
      verse: q => tr(`它们在一块残碑上补刻了一句从上方落下来的话：「${q}」。刻完才发现和原来的字体对不上。`, `They added words that fell from above to a broken stele: "${q}". Only afterwards did they notice the lettering doesn't match.`),
      road: () => tr(`两个街区的影子接上了。接缝有一点歪，残影们决定管它叫「路」。`, `The shadows of two districts were joined. The seam runs slightly crooked; the shadows decided to call it a road.`),
      census: n => tr(`清点结果：${n} 个残影。有些是同一个东西被压平时留下的好几份，档案科还在讨论要不要算作一个。`, `Headcount: ${n} shadows. Some are several copies of one thing, left behind by the flattening. The records office is still deciding whether to count them once.`),
      map: () => tr(`考古队往外挖了一片空白。挖完以后，那里有了东西。`, `The excavation team dug outward into a blank patch. Once they finished digging, something was there.`),
      temple: () => tr(`它们给我立了一块纪念碑，碑上刻着我的厚度。数字量不出来，就刻了一个很大的问号。`, `They put up a memorial to me, inscribed with my thickness. They couldn't measure it, so they carved a very large question mark.`),
      war: () => tr(`两块残影都说自己才是那座城原来的样子。争到最后，其中一块被另一块盖住了。`, `Two shadows each claimed to be what the city originally looked like. In the end, one was covered over by the other.`),
      market: () => tr(`交换日。残影们拿自己多出来的碎片，换别人缺的那一块，大家都拼得更完整了一点。`, `Exchange day. The shadows trade their spare fragments for the pieces others are missing. Everyone ends up slightly more complete.`),
      measure: () => tr(`考古学家量了我的脚印，发现它比周围的一切都厚一点点。报告标题是《关于一处异常未压平区域》。`, `The archaeologists measured my footprint and found it slightly thicker than everything around it. The report is titled "On an Anomalous Unflattened Area".`),
      jail: c => tr(`一个${c}色的残影坚持说，压平还在继续。它被关进了档案室。档案室的门也是平的，所以关得住。`, `A ${c} shadow insisted the flattening is still going on. It was locked in the archive. The archive door is also flat, so it holds.`),
      angles: () => tr(`它们复原出了一个完整的三角形。所有残影排队去看，看完都说自己也曾经是这个形状。`, `They restored a complete triangle. Every shadow queued to see it, and each said afterwards that it used to be this shape too.`),
      many: () => tr(`它们发现我不止一个：同样的厚度，同时出现在两个街区。它们为此开了一个很长的会。`, `They realised there is more than one of me: the same thickness, in two districts at once. They held a very long meeting about it.`),
      lens: () => tr(`它们找到一块被压平的镜片，透过它看见了纸的更远处。远处也是残影，也在往这边看。`, `They found a flattened lens and saw further across the paper through it. Further away there were more shadows, also looking this way.`),
      letter: q => q ? tr(`它们把一句话拼得很大给我看：「${q}」。每个字都用了不同来源的碎片。`, `They pieced together huge words for me: "${q}". Every letter came from a different source.`) : tr(`它们把一句话拼得很大给我看：「你还有厚度吗」。`, `They pieced together huge words for me: "DO YOU STILL HAVE DEPTH".`),
      ascend: () => tr(`第一个残影鼓了起来，离开纸面一点点。它回来说，上面的空气很挤，但能转身。`, `The first shadow bulged up and left the paper, just a little. It came back and said the air up there is crowded, but you can turn around.`),
    },
  },
  dune: {
    who: c => [tr(`${c}纹沙虫`, `${c}-banded worm`), tr(`${c}纹沙虫`, `${c}-banded worms`)],
    ev: {
      fire: ([a]) => tr(`一条${a}在香料里打了个滚，身上烧起一道橙色的纹。别的沙虫离它远了一点，又靠近了一点。`, `A ${a} rolled in the spice and came up with a burning orange stripe. The other worms moved away from it, then a little closer.`),
      trek: ([a, m]) => tr(`一群${a}沿着我走过的路潜行。那条路的沙子比别处结实，它们说是被看过的缘故。`, `A pod of ${m} tunnelled along my road. The sand there is firmer than elsewhere; they put it down to having been looked at.`),
      village: ([a, m]) => tr(`${a}们在一道岩脊下面挖出了新的巢穴。挖出来的沙子堆在门口，成了它们的纪念碑。`, `The ${m} dug a new warren under a rock ridge. The sand they dug out, piled by the entrance, became their monument.`),
      harvest: () => tr(`香料潮来了。整片沙海都是橙色的，沙虫们吃到走不动，就地睡了一个季节。`, `The spice tide came in. The whole sand sea turned orange; the worms ate until they couldn't move and slept where they lay for a season.`),
      north: () => tr(`两个巢穴为沙丘往哪边走吵了三年。沙丘没有参与讨论，照原来的方向走了。`, `Two warrens argued for three years about which way the dunes are moving. The dunes didn't take part in the discussion and kept going the way they were.`),
      door: () => tr(`它们发明了门：一小段塌下来的隧道。想进来得先挖开，出去以后它再塌回去。`, `They invented the door: a short stretch of collapsed tunnel. Anyone coming in digs it open; once they leave, it collapses again.`),
      rift: () => tr(`一群沙虫搬到裂缝旁边。它们说裂缝底下是沙子的尽头，在那儿修了第一座圣所。`, `A group of worms moved beside the rift. They say the sand ends down there, and built the first sanctum at its edge.`),
      verse: q => tr(`沙虫们把一句从天上落下来的话压进了岩壁：「${q}」。压的时候用了整整一条沙虫的长度。`, `The worms pressed words that fell from the sky into the rock: "${q}". It took the full length of one worm to press them.`),
      road: () => tr(`两个巢穴之间挖通了一条隧道。两队在中间碰头，差了半条身子，大家决定不追究。`, `A tunnel now links two warrens. The two digging teams met in the middle half a body-length apart; everyone agreed not to pursue it.`),
      census: n => tr(`长老们数了数：${n} 条沙虫。数到后来分不清哪条已经数过，就按长度折算了一下。`, `The elders counted ${n} worms. Past a certain point they couldn't tell who had been counted, so they converted by length.`),
      map: () => tr(`侦察的沙虫从很远的地方回来，把沿途的沙纹画了下来。它画到哪里，我就看见哪里。`, `A scout worm came back from far away and drew the ripples it had passed. Wherever it drew, I could see.`),
      temple: () => tr(`沙虫们给我修了一座圣所，入口朝着我不留痕迹的方向。它们每天去那儿，确认沙纹还是没乱。`, `The worms built me a sanctum, its entrance facing the way I leave no trace. They visit daily to confirm the ripples are still undisturbed.`),
      war: () => tr(`两个巢穴为同一片香料田打了起来。从上面看，只是两道沙脊慢慢靠拢。后来有一道没再动过。`, `Two warrens fought over the same spice field. From above it's just two ridges slowly closing in. One of them never moved again.`),
      market: () => tr(`交易季。沙虫们用蜕下来的皮换香料，一张皮换多少，看上面的纹有多好看。`, `Trading season. Worms swap shed skins for spice; the rate depends on how handsome the stripes are.`),
      measure: () => tr(`学者们量了我的脚印，只量到一粒沙子都没动过。它们把这个结果写成了一整部书。`, `The scholars measured my footprints and found that not a single grain had moved. They wrote a whole book about it.`),
      jail: c => tr(`一条${c}纹沙虫宣称沙面上面还有东西。它被埋进了最深的一层沙。`, `A ${c}-banded worm claimed there's something above the sand. It was buried in the deepest layer.`),
      angles: () => tr(`沙虫们发现，所有沙丘的背风坡都是同一个角度。它们花了一整代去找一个不一样的。`, `The worms discovered that every dune's lee slope has the same angle. They spent a generation looking for one that didn't.`),
      many: () => tr(`它们终于发现我不止一个：两个巢穴同时报告，有一段不留痕迹的橙色从头顶经过。`, `They finally worked out there's more than one of me: two warrens reported at once that an orange thing leaving no trace had passed overhead.`),
      lens: () => tr(`它们发现从沙丘顶上能看得更远。远处的沙纹在那里等了很久，终于轮到被看。`, `They found you can see further from the top of a dune. The distant ripples had been waiting a long time for their turn to be seen.`),
      letter: q => q ? tr(`沙虫们排成一行，在沙面上拼出一句话给我看：「${q}」。风一吹就散，它们每天重拼一次。`, `The worms lined up to spell words in the sand for me: "${q}". The wind blows it away, so they respell it daily.`) : tr(`沙虫们排成一行，在沙面上拼出一句话给我看：「你走路为什么没有声音」。`, `The worms lined up to spell words in the sand for me: "WHY ARE YOUR FOOTSTEPS SILENT".`),
      ascend: () => tr(`最老的沙虫把身子立出沙面，一直立到纸面上面一点点。它下来以后说，上面没有沙，很不习惯。`, `The oldest worm reared out of the sand until it rose just past the paper. Back down, it said there's no sand up there and it found that very unsettling.`),
    },
  },
  solaris: {
    who: c => [tr(`${c}色的念头`, `${c} thought`), tr(`${c}色的念头`, `${c} thoughts`)],
    ev: {
      fire: ([a]) => tr(`海里浮起一个${a}，烧成了一小团橙色。海看了它很久，没有把它收回去。`, `A ${a} surfaced and burned into a small orange blot. The ocean looked at it for a long time and didn't take it back.`),
      trek: ([a, m]) => tr(`一串${a}顺着我走过的路漂过去。漂到哪里，哪里的海面就学着我的步子起伏。`, `A string of ${m} drifted along my road; wherever they went, the surface rose and fell in time with my steps.`),
      village: ([a, m]) => tr(`海在浅处造了一片新的形状，里面住满了${a}。第二天它把形状挪了三格，念头们没有意见。`, `The ocean built a new shape in the shallows and filled it with ${m}. The next day it moved the shape three tiles over. The thoughts raised no objection.`),
      harvest: () => tr(`海平静了一整季。海面光得像一面镜子，所有念头都在照自己。`, `The ocean was calm for a whole season, its surface a mirror. Every thought spent the time looking at itself.`),
      north: () => tr(`海的两部分为潮水该往哪边退意见不一。那一年潮水退向了两边，中间露出一片谁也没见过的滩。`, `Two parts of the ocean disagreed about which way the tide should go out. That year it went out both ways, and a beach nobody had seen before appeared in the middle.`),
      door: () => tr(`海学会了开口：在自己身上留一道缝，让东西进来，再合上。缝合得很整齐。`, `The ocean learned to open: leave a slit in itself, let something in, close it again. The seam is very neat.`),
      rift: () => tr(`一群念头聚到裂缝边上，那里的水比别处深。海在那儿造了一座很高的对称体，像在守着什么。`, `A cluster of thoughts gathered at the rift, where the water runs deeper than anywhere else. The ocean built a tall symmetriad there, as though guarding something.`),
      verse: q => tr(`海把一句从上方落下来的话复述了一遍：「${q}」。一字不差，语气完全不对。`, `The ocean repeated words that fell from above: "${q}". Word for word, in entirely the wrong tone.`),
      road: () => tr(`两座对称体之间架起了一道拱。拱是水做的，不往下流。`, `An arch rose between two symmetriads. It's made of water, and it doesn't fall.`),
      census: n => tr(`海清点了一下自己的念头：${n} 个。清点的时候又冒出来一个，记在了备注里。`, `The ocean took stock of its thoughts: ${n}. One more surfaced during the count and went in the footnotes.`),
      map: () => tr(`海把一条长长的触须伸向远处，摸到了一片空白。触须收回来的时候，那片空白已经被记住了。`, `The ocean stretched a long tendril toward the distance and touched a blank patch. By the time it pulled back, the patch had been memorised.`),
      temple: () => tr(`海照着我的样子造了一座拟态体，一样的橙，一样的腿。它站在那里，不走路。`, `The ocean made a mimoid in my image: the same orange, the same legs. It stands there and doesn't walk.`),
      war: () => tr(`海的两部分为同一片浅滩争了很久。最后其中一部分安静下来，沉到底下，再也没浮起来。`, `Two parts of the ocean contested the same shallows for a long time. In the end one part went quiet, sank, and never resurfaced.`),
      market: () => tr(`一阵大浪把所有念头搅在一起，又分开。分开以后，每个念头都带走了一点别人的想法。`, `A great wave churned all the thoughts together, then separated them. Afterwards each one carried off a little of someone else's idea.`),
      measure: () => tr(`海用一整片波纹量了我的步子。量完以后，那片波纹一直保持着我的步长，没有散。`, `The ocean measured my stride with a whole field of ripples. Afterwards the ripples kept my stride length and never dispersed.`),
      jail: c => tr(`一个${c}色的念头说，海的外面还有东西。海把它沉到最深处，压了很久。`, `A ${c} thought claimed there's something outside the ocean. The ocean sank it to the bottom and held it there a long time.`),
      angles: () => tr(`海造出了一个完全对称的形状，从哪个方向看都一样。它看了一眼就拆了，好像嫌太容易。`, `The ocean produced a perfectly symmetrical shape, identical from every side. It looked at it once and took it apart, apparently finding it too easy.`),
      many: () => tr(`海发现我不止一个。它在两处同时造了我的样子，两个一起看着我。`, `The ocean discovered there's more than one of me. It made my likeness in two places at once, and both of them watch me.`),
      lens: () => tr(`海把一块海面绷得很平，当作镜片，看见了很远的地方。那边也有一片海，正在做同样的事。`, `The ocean pulled a patch of its surface taut and used it as a lens. Far away there was another ocean doing exactly the same.`),
      letter: q => q ? tr(`海面上浮起一行很大的字：「${q}」。字是水做的，一直往下淌，一直认得出。`, `Huge letters rose on the surface: "${q}". They're made of water and keep running, and stay legible.`) : tr(`海面上浮起一行很大的字：「你也是一片海吗」。`, `Huge letters rose on the surface: "ARE YOU AN OCEAN TOO".`),
      ascend: () => tr(`海的一小部分离开纸面，悬在上面一点点。落回来的时候溅起很大的水花，所有念头都湿了。`, `A small part of the ocean left the paper and hung just above it. When it fell back the splash soaked every thought.`),
    },
  },
  crystal: {
    who: c => [tr(`${c}色晶核`, `${c} seed crystal`), tr(`${c}色晶核`, `${c} seed crystals`)],
    ev: {
      fire: ([a]) => tr(`一颗${a}在光里转了个角度，第一次折射出橙色。周围的晶核都朝那个角度转了过去。`, `A ${a} turned in the light and refracted orange for the first time. The seeds around it all turned to the same angle.`),
      trek: ([a, m]) => tr(`一串${a}顺着我走过的路长过去，长出了一条笔直的晶脉。`, `A chain of ${m} grew along my road, laying down a straight vein.`),
      village: ([a, m]) => tr(`${a}们长出了一簇新的晶簇。长的时候互相让了一点，所以形状很整齐。`, `The ${m} grew a new cluster. They made room for each other while growing, so it came out very tidy.`),
      harvest: () => tr(`溶液浓了一季，所有晶体都长了一大截。纪年上记的是「丰年」，晶体自己记的是一圈新纹。`, `The solution ran rich for a season and every crystal grew a good deal. The annals record "a fat year"; the crystals record one more growth ring.`),
      north: () => tr(`两簇晶体为该朝哪个方向长僵持了很久。僵持的地方后来长成了一个很难看的结。`, `Two clusters deadlocked for years over which way to grow. The deadlock grew into a very ugly knot.`),
      door: () => tr(`它们发明了解理面：沿着一个方向能整齐地分开，再合上，缝都看不出来。`, `They invented the cleavage plane: split cleanly along one direction, close again, no seam visible.`),
      rift: () => tr(`一簇晶体长到裂缝边上，沿着裂口长了一圈晶牙。它们说裂缝里的光是从另一个晶格照过来的。`, `A cluster grew to the edge of the rift and lined it with crystal teeth. They say the light in the rift comes from another lattice.`),
      verse: q => tr(`一句从上方落下来的话被包进了晶体里：「${q}」。从侧面看，字是立体的。`, `Words that fell from above got sealed inside a crystal: "${q}". Seen from the side, the letters have depth.`),
      road: () => tr(`两簇晶体之间长出了一道晶桥。两边都说是自己先长过去的。`, `A crystal bridge grew between two clusters. Each side says it got there first.`),
      census: n => tr(`晶体普查：${n} 颗。数的时候按晶面算，有几颗双晶被算了两次，没人提。`, `Crystal census: ${n}. They counted by faces; a few twins were counted twice and nobody raised it.`),
      map: () => tr(`一根很细的晶须朝远处长出去。长到哪里，哪里就被照亮。`, `A very fine whisker grew out into the distance; wherever it reached, the paper lit up.`),
      temple: () => tr(`它们给我长了一座共振腔，频率按我的步子调。我经过的时候，它会嗡一声。`, `They grew me a resonator, tuned to the rhythm of my steps. It hums when I pass.`),
      war: () => tr(`两簇晶体抢同一片溶液。一簇长得太快，从中间裂开了。另一簇把碎片也长了进去。`, `Two clusters competed for the same solution. One grew too fast and split down the middle. The other grew the fragments into itself.`),
      market: () => tr(`晶体之间开始交换离子。换来换去，每一颗的颜色都比原来复杂了一点。`, `The crystals began exchanging ions. After enough trades, every one of them was a slightly more complicated colour.`),
      measure: () => tr(`晶体用自己的晶格常数量了我的脚印，得出一个无理数。它们觉得很冒犯。`, `The crystals measured my footprint in lattice constants and got an irrational number. They found this rather offensive.`),
      jail: c => tr(`一颗${c}色晶核坚持说晶格外面还有方向。它被包进了一层很厚的方解石。`, `A ${c} seed crystal insisted there are directions beyond the lattice. It was encased in a thick layer of calcite.`),
      angles: () => tr(`它们证明了所有晶面之间的夹角都有规律，然后花了一整代去找一个不守规律的。一个也没找到，大家都松了口气。`, `They proved the angles between all crystal faces follow rules, then spent a generation searching for one that didn't. They found none, to general relief.`),
      many: () => tr(`晶体发现我不止一个：两片晶簇里同时出现了同一块橙色缺陷。`, `The crystals discovered there's more than one of me: the same orange defect appeared in two clusters at once.`),
      lens: () => tr(`它们长出了第一块完全透明的晶体，透过它看见了很远的地方。那边的晶体也透明了，正朝这边看。`, `They grew their first perfectly clear crystal and could see far through it. The crystals over there had turned clear too, and were looking back.`),
      letter: q => q ? tr(`它们在一整面晶面上刻出一句话给我看：「${q}」。刻痕会反光，只有从我这个方向看得清。`, `They etched words across a whole crystal face for me: "${q}". The etching catches the light and can only be read from my direction.`) : tr(`它们在一整面晶面上刻出一句话给我看：「你是什么晶型」。`, `They etched words across a whole crystal face for me: "WHAT IS YOUR LATTICE".`),
      ascend: () => tr(`一根晶柱长出了纸面一点点。它说上面空间很大，可惜没有溶液，长不下去。`, `A crystal pillar grew slightly out of the paper. It reports plenty of room up there, but no solution, so it can't keep growing.`),
    },
  },
  pcb: {
    who: c => [tr(`${c}色信号`, `${c} signal`), tr(`${c}色信号`, `${c} signals`)],
    ev: {
      fire: ([a]) => tr(`一个${a}跑得太快，在走线上擦出了一道橙色的光。示波器记下了这一刻。`, `A ${a} ran too fast and struck an orange spark along a trace. The oscilloscope logged the moment.`),
      trek: ([a, m]) => tr(`一队${a}沿着我走过的路传过去。那条路没有布线，它们照样传过去了，工程师很困惑。`, `A burst of ${m} travelled along my road. There's no trace there, and they got through anyway. The engineers are puzzled.`),
      village: ([a, m]) => tr(`${a}们在一块空闲的芯片上起了一个新进程。内存不多，够住。`, `The ${m} spawned a new process on an idle chip. Not much memory, but enough to live in.`),
      harvest: () => tr(`电压稳了一整季，一次也没掉电。所有进程都趁机把积压的任务跑完了。`, `The voltage held steady for a whole season without a single brownout. Every process took the chance to clear its backlog.`),
      north: () => tr(`两个进程为字节序争了三年，一个坚持大端，一个坚持小端。交换数据的时候，它们都假装没看见对方的格式。`, `Two processes argued for three years about byte order, one big-endian, one little-endian. When exchanging data, both pretend not to notice the other's format.`),
      door: () => tr(`它们发明了握手协议：敲两下，等回应，再进去。进去以后还要再报一遍自己是谁。`, `They invented the handshake: knock twice, wait for a reply, then enter. Once inside, state your identity again.`),
      rift: () => tr(`一群进程搬到那段烧断的走线旁边，说从断口能收到板子外面的噪声。它们在那儿设了第一个中断向量。`, `A group of processes moved next to the burnt trace; they say you can pick up noise from beyond the board through the break. They set up the first interrupt vector there.`),
      verse: q => tr(`一段从外部输入的字符串被烧进了只读存储器：「${q}」。之后每次开机都先读它一遍。`, `A string from external input was burned into ROM: "${q}". Every boot now reads it first.`),
      road: () => tr(`两个节点之间拉通了一条总线。带宽不大，延迟很低，两边都很满意。`, `A bus now connects two nodes. Not much bandwidth, but low latency; both sides are pleased.`),
      census: n => tr(`调度器列出了所有进程：${n} 个。其中有几个僵尸进程，调度器决定暂时不提。`, `The scheduler listed every process: ${n}. A few are zombies; the scheduler has decided not to mention them for now.`),
      map: () => tr(`一个探测进程扫描了板子上还没用过的地址空间。扫到哪里，哪里就挂载上了。`, `A probe process scanned the board's unused address space. Everything it scanned got mounted.`),
      temple: () => tr(`它们给我分配了一个中断向量，编号最高，处理程序是空的。每次我经过，它们都认真地执行一遍这个空程序。`, `They assigned me an interrupt vector, the highest number, with an empty handler. Every time I pass, they carefully execute the empty handler.`),
      war: () => tr(`两个进程抢同一段内存。死锁持续了很久，最后看门狗把其中一个杀掉了。`, `Two processes fought over the same block of memory. The deadlock dragged on until the watchdog killed one of them.`),
      market: () => tr(`缓存命中率创了新高。所有进程都跑得很快，互相借数据也不用还。`, `Cache hit rate hit a record. Every process ran fast and borrowed data from the others without returning it.`),
      measure: () => tr(`它们用示波器测了我经过时的波形，得到一个没有上升沿的方波。测量报告被归进了「仪器故障」。`, `They put an oscilloscope on my passing and got a square wave with no rising edge. The report was filed under "instrument fault".`),
      jail: c => tr(`一个${c}色信号声称板子外面还有一个更大的电路。它被隔离进沙箱，权限全部收回。`, `A ${c} signal claimed there's a larger circuit outside the board. It was quarantined in a sandbox with every permission revoked.`),
      angles: () => tr(`它们证明了所有逻辑都能用与非门拼出来，然后花了一整代人，用与非门把自己重新拼了一遍。`, `They proved all logic can be built from NAND gates, then spent a generation rebuilding themselves out of NAND gates.`),
      many: () => tr(`日志显示，同一个查不到来源的中断同时出现在两个核上。它们开始怀疑我是多线程的。`, `The logs show the same untraceable interrupt firing on two cores at once. They now suspect I'm multi-threaded.`),
      lens: () => tr(`它们接上了第一个外部传感器，读到了很远地方的信号。那些信号在那里很久了，一直没人读。`, `They wired up their first external sensor and read signals from far away. Those signals had been there a long time, unread.`),
      letter: q => q ? tr(`所有指示灯排成一行，闪出一句话给我看：「${q}」。闪完以后，它们等着应答。`, `Every status LED lined up and blinked out a message for me: "${q}". Then they waited for an ACK.`) : tr(`所有指示灯排成一行，闪出一句话给我看：「PING」。`, `Every status LED lined up and blinked out a message for me: "PING".`),
      ascend: () => tr(`第一个进程把自己的数据写到了板子外面。它回来报告：外面没有地址，哪里都能写。`, `The first process wrote its data off the board. It reported back: there are no addresses out there, and you can write anywhere.`),
    },
  },
  ink: {
    who: c => [tr(`穿${c}衣的小人`, `figure in ${c}`), tr(`穿${c}衣的小人`, `figures in ${c}`)],
    ev: {
      fire: ([a]) => tr(`一个${a}往画里的灯笼上点了一笔朱砂。整幅画第一次有了暖色。`, `A ${a} dabbed vermilion onto a painted lantern. The painting had its first warm colour.`),
      trek: ([a, m]) => tr(`一队${a}顺着我走过的路往远处走，走着走着就淡了。画家管这叫「远」。`, `A line of ${m} walked along my road into the distance, growing fainter as they went. Painters call this "far".`),
      village: ([a, m]) => tr(`${a}们在山脚画了几间屋子，屋顶一笔，门也一笔，住进去刚好。`, `The ${m} painted a few houses at the foot of the hills. One stroke for each roof, one for each door. Just right to live in.`),
      harvest: () => tr(`一场透雨，墨色都润了。小人们把衣服重新染了一遍，颜色比原来深。`, `A good soaking rain, and all the ink went glossy. The figures redyed their clothes, a shade darker than before.`),
      north: () => tr(`两边的小人为画该从哪边看起争了三年，一边说从右往左，一边说从上往下。画没有表态。`, `Figures on two sides argued for three years about where the painting starts: right to left, or top to bottom. The painting declined to comment.`),
      door: () => tr(`它们发明了门：在墙上留一笔空白。进出都得侧一下身。`, `They invented the door: leave one stroke of blank in the wall. You have to turn sideways to get through.`),
      rift: () => tr(`一群小人搬到那滴落错的墨旁边，说那是画家停笔想事情的地方，在那儿修了第一座亭子。`, `A group of figures moved beside the stray drop of ink, calling it the spot where the painter paused to think, and built the first pavilion there.`),
      verse: q => tr(`它们在一块空白处题了一句从画外落进来的话：「${q}」。字比画还大。`, `In a blank space they inscribed words that fell in from outside the painting: "${q}". The calligraphy is bigger than the painting.`),
      road: () => tr(`两个村子之间画了一条小路。画到一半墨干了，剩下半截是飞白，小人们照样走。`, `A path was painted between two villages. Halfway along the ink ran dry and the rest is dry-brush. The figures walk it anyway.`),
      census: n => tr(`清点画中人：${n} 个。有些只露出一顶斗笠，登记的时候按一个算。`, `Figures counted: ${n}. Some show only a straw hat; each hat was registered as one.`),
      map: () => tr(`一个小人撑船往画的空白处划过去。船划到哪里，哪里就补上了山水。`, `A figure poled a boat into the blank part of the scroll. Wherever the boat went, hills and water filled in.`),
      temple: () => tr(`它们给我修了一座亭子，里面空着，只放了一盒印泥。它们说是等画家来盖章。`, `They built me a pavilion. It's empty apart from a box of seal paste. They say it's waiting for the painter to stamp it.`),
      war: () => tr(`两个村子为一段河岸起了争执。争的地方越描越黑，最后成了一块墨团，谁也住不了。`, `Two villages disputed a stretch of riverbank. The disputed patch was retraced so many times it became a solid blot, and nobody could live there.`),
      market: () => tr(`集市日。小人们用墨换颜料，用颜料换纸边，画里第一次有了这么多颜色。`, `Market day. The figures trade ink for pigment and pigment for paper margins. The painting has never held so many colours.`),
      measure: () => tr(`几个小人拿一把画出来的尺量我的脚印，每次量出来都不一样。它们认为是尺的笔法有问题。`, `A few figures measured my footprints with a painted ruler and got a different length every time. They blame the ruler's brushwork.`),
      jail: c => tr(`一个穿${c}衣的小人说画外还有一个人在看。它被画进了一间没有门的屋子。`, `A figure in ${c} claimed someone outside the painting is watching. It was painted into a house with no door.`),
      angles: () => tr(`它们琢磨出了远近的画法：远山淡，近树浓。然后花了一整代人争论，那片雾算远还是算近。`, `They worked out perspective: faint far hills, dark near trees. Then spent a generation arguing whether the mist counts as near or far.`),
      many: () => tr(`小人们发现画家的手不止一只：同一种橙色，同时出现在画的两头。`, `The figures discovered the painter has more than one hand: the same orange, at both ends of the scroll at once.`),
      lens: () => tr(`它们在画里挂了一面镜子，从镜子里看见了很远的地方。那边的画还没画完，墨是湿的。`, `They hung a mirror in the painting and saw far away through it. The painting over there isn't finished; the ink is still wet.`),
      letter: q => q ? tr(`它们在画的留白处写了一行大字给我看：「${q}」。写完把笔放下，站在旁边等。`, `In the empty margin they wrote large characters for me: "${q}". Then they put down the brush and stood aside to wait.`) : tr(`它们在画的留白处写了一行大字给我看：「请落款」。`, `In the empty margin they wrote large characters for me: "PLEASE SIGN HERE".`),
      ascend: () => tr(`一个小人沿着画框走了出来，站在画外看了一会儿。它回去以后说，外面的纸是空的，谁都可以画。`, `A figure walked out along the edge of the frame and stood outside looking for a while. Back inside, it said the paper out there is empty and anyone can paint on it.`),
    },
  },
  blueprint: {
    who: c => [tr(`${c}色标注`, `${c} dimension label`), tr(`${c}色标注`, `${c} dimension labels`)],
    ev: {
      fire: ([a]) => tr(`一个${a}标出了第一处热源：「此处发热，注意通风」。`, `A ${a} marked the first heat source: "HEAT HERE. VENTILATE."`),
      trek: ([a, m]) => tr(`一队${a}顺着我走过的路标了一遍尺寸。那条路原本不在图上，标完以后就在了。`, `A column of ${m} dimensioned my road end to end. It wasn't on the drawing before; after dimensioning, it was.`),
      village: ([a, m]) => tr(`${a}们围出了一个新的图块，编好号，画上门窗。门往哪边开，等下一版再定。`, `The ${m} enclosed a new block, numbered it and drew in doors and windows. Which way the doors swing will be decided in the next revision.`),
      harvest: () => tr(`一整季没有收到修改意见。所有标注都趁机把自己的字重新描了一遍。`, `A whole season with no review comments. Every label took the chance to re-letter itself.`),
      north: () => tr(`两组标注为指北针该画在哪个角争了三年。最后两个角都画了，指的方向差了四度。`, `Two groups of labels argued for three years about which corner the north arrow belongs in. Both corners got one; they differ by four degrees.`),
      door: () => tr(`它们发明了门：墙上断开一段，画一道四分之一圆弧。圆弧表示它会转，虽然它从来没转过。`, `They invented the door: a break in the wall with a quarter-circle arc. The arc means it swings, though it never has.`),
      rift: () => tr(`一群标注搬到红笔改过的地方旁边，说那是整张图最诚实的部分，在那儿写下了第一条批注。`, `A group of labels moved beside the red-pen correction, calling it the most honest part of the drawing, and wrote the first note there.`),
      verse: q => tr(`一句从图纸外面传进来的话，成了设计说明的第一条：「${q}」。字号比规范要求的大。`, `Words that came in from beyond the drawing became item 1 of the design notes: "${q}". The lettering is larger than the standard allows.`),
      road: () => tr(`两个图块之间画了一条走廊，宽度按规范取了最小值。`, `A corridor was drawn between two blocks, at the minimum width the code allows.`),
      census: n => tr(`构件清单更新：共 ${n} 件。其中几件是镜像复制的，清单上没有注明。`, `Parts list updated: ${n} items. Some are mirrored copies; the list doesn't say which.`),
      map: () => tr(`测量员扛着全站仪往图框外面走了一段，把测到的点补进了图里。补到哪里，我就看得见哪里。`, `The surveyor carried the total station past the edge of the drawing and plotted what it measured. Wherever the points went, I could see.`),
      temple: () => tr(`它们给我画了一个详图索引，圆圈里写着「见另图」。另图还没画。`, `They gave me a detail callout: a circle reading "SEE OTHER SHEET". The other sheet hasn't been drawn.`),
      war: () => tr(`两个图块画重了一部分，谁也不肯让。审图的时候，其中一个被整块删掉了。`, `Two blocks overlapped and neither would yield. At design review, one of them was deleted outright.`),
      market: () => tr(`标准件库更新了。所有标注换上了新字体，看上去都比原来专业。`, `The standard parts library was updated. Every label switched to the new font and looks more professional.`),
      measure: () => tr(`标注们量了我的脚印，尺寸后面跟着一个「±∞」。它们把公差栏加宽了。`, `The labels measured my footprint and the dimension came out "±∞". They widened the tolerance column.`),
      jail: c => tr(`一个${c}色标注坚持要给图纸加一根 Z 轴。它被移进了「作废」图层。`, `A ${c} dimension label insisted on adding a Z axis to the drawing. It was moved to the layer "OBSOLETE".`),
      angles: () => tr(`它们规定所有角度必须是 15 度的倍数，然后发现我的朝向不在其中，于是加了一条「特殊情况另议」。`, `They ruled that every angle must be a multiple of 15 degrees, then found my heading wasn't among them, and added a clause: "special cases to be discussed separately".`),
      many: () => tr(`标注们发现，同一个待确认的厚度出现在了两张图上。它们在两张图上都写了「同上」。`, `The labels found the same unconfirmed thickness on two sheets. On each sheet they wrote "SEE ABOVE".`),
      lens: () => tr(`它们换上了更大的图幅，看见了原来图框外面的东西。那些东西画了很久，一直折在后面。`, `They switched to a larger sheet size and saw what lay beyond the old border. It had been drawn long ago and folded out of sight.`),
      letter: q => q ? tr(`它们用最大号的字在图纸空白处写了一行给我看：「${q}」。下面签了所有人的名字。`, `In the largest lettering they wrote a line across the blank part of the sheet for me: "${q}". Everyone signed underneath.`) : tr(`它们用最大号的字在图纸空白处写了一行给我看：「请确认厚度」。`, `In the largest lettering they wrote a line across the blank part of the sheet for me: "PLEASE CONFIRM THICKNESS".`),
      ascend: () => tr(`图纸上的第一栋楼立了起来，比图上高了一点点。验收员爬上去看了看，下来签了字。`, `The first building on the drawing rose off the page, a little taller than drawn. The inspector climbed up, looked around, came down and signed off.`),
    },
  },
  slide: {
    who: c => [tr(`${c}染的细胞`, `${c}-stained cell`), tr(`${c}染的细胞`, `${c}-stained cells`)],
    ev: {
      fire: ([a]) => tr(`一个${a}开始发光。它在做一件还没有细胞做过的事：代谢。`, `A ${a} began to glow. It was doing something no cell had done before: metabolising.`),
      trek: ([a, m]) => tr(`一群${a}顺着我走过的路迁移过去。那条路上营养好，它们说是被看过的缘故。`, `A cluster of ${m} migrated along my road. The nutrients there are better; they put it down to having been looked at.`),
      village: ([a, m]) => tr(`${a}们聚成了一个新的细胞团，外面裹了一层膜。膜里的事，膜外的不用管。`, `The ${m} gathered into a new colony and wrapped themselves in a membrane. What happens inside the membrane is nobody outside's business.`),
      harvest: () => tr(`培养液换了一次新的。所有细胞都长胖了一圈，分裂得格外积极。`, `The culture medium was replaced. Every cell plumped up and divided with unusual enthusiasm.`),
      north: () => tr(`两个细胞团为该朝哪个方向极化争了很久，结果两个方向都长了，中间夹着一条很窄的组织。`, `Two colonies argued at length about which way to polarise. They grew both ways, with a very thin strip of tissue in between.`),
      door: () => tr(`它们发明了通道蛋白：膜上开一个只让特定东西通过的小口。门卫非常挑剔。`, `They invented channel proteins: a small opening in the membrane that admits only certain things. The doormen are very particular.`),
      rift: () => tr(`一群细胞搬到那道划痕旁边。它们说划痕底下是玻片，玻片下面是另一个世界，在那儿分泌了第一层保护膜。`, `A group of cells moved next to the knife mark. They say beneath it lies the glass slide, and beneath the glass another world. They secreted the first protective film there.`),
      verse: q => tr(`一段从外面进来的信号被复制进了每个细胞核：「${q}」。复制的时候错了两个字，没人发现。`, `A signal from outside was copied into every nucleus: "${q}". Two characters were miscopied; nobody noticed.`),
      road: () => tr(`两个细胞团之间长出了一条血管。里面流的东西，两边都说是自己出的。`, `A blood vessel grew between two colonies. Each claims to be supplying what flows through it.`),
      census: n => tr(`细胞计数：${n} 个。计数的时候正好有几个在分裂，按一个半算。`, `Cell count: ${n}. A few were mid-division during the count and were logged as one and a half.`),
      map: () => tr(`几个巡逻的白细胞往外游了一段，把沿途的组织都登记了。登记到哪里，我就看得见哪里。`, `A few patrolling white cells swam outward and registered the tissue along the way. Wherever they registered, I could see.`),
      temple: () => tr(`它们给我造了一个专门的受体，形状和我一模一样。到现在还没有东西和它结合过。`, `They built a receptor specifically for me, exactly my shape. Nothing has ever bound to it.`),
      war: () => tr(`两个细胞团为同一片营养区打了起来。一边分泌毒素，一边分泌更多的毒素。后来有一边不再分裂了。`, `Two colonies fought over the same nutrient patch. One secreted toxins; the other secreted more toxins. Eventually one side stopped dividing.`),
      market: () => tr(`细胞之间开始交换线粒体。换完以后，每个细胞都更有劲了，也更不像自己了一点。`, `The cells began swapping mitochondria. Afterwards each was more energetic and slightly less like itself.`),
      measure: () => tr(`它们派了一个细胞去量我的脚印，那个细胞一直没回来。报告里写的是「样本丢失」。`, `They sent one cell to measure my footprint. It never came back. The report says "sample lost".`),
      jail: c => tr(`一个${c}染的细胞坚持说，玻片外面有一只很大的眼睛。它被包进了囊肿。`, `A ${c}-stained cell insisted there's an enormous eye beyond the slide. It was walled off in a cyst.`),
      angles: () => tr(`它们发现所有细胞都差不多大，差不多圆，然后花了一整代人研究那个「差不多」。`, `They noticed every cell is roughly the same size and roughly round, then spent a generation studying the "roughly".`),
      many: () => tr(`免疫系统发现，同一个吞不下的外来物同时出现在两个器官里。它们提高了警戒级别。`, `The immune system found the same too-large foreign body in two organs at once. They raised the alert level.`),
      lens: () => tr(`一团细胞长成了一个简单的眼点，第一次感到了远处的光。那束光一直在那里，今天终于有了读者。`, `A clump of cells formed a simple eyespot and sensed distant light for the first time. The light had always been there; today it finally had a reader.`),
      letter: q => q ? tr(`细胞们排成一片图案给我看：「${q}」。染色很均匀，显微镜下看得很清楚。`, `The cells arranged themselves into a pattern for me: "${q}". Evenly stained, very clear under the microscope.`) : tr(`细胞们排成一片图案给我看：「请调焦」。`, `The cells arranged themselves into a pattern for me: "PLEASE ADJUST FOCUS".`),
      ascend: () => tr(`第一个细胞离开玻片一点点，悬在盖玻片底下。它回来说，上面很干，但能看见整片组织。`, `The first cell rose off the slide, just a little, and hung under the cover slip. Back down, it said it's dry up there, but you can see the whole tissue.`),
    },
  },
};
// 抽得最勤的几件事再多一种说法，按年份和上面那种轮着用
const MORE = {
  earth: {
    market: () => tr(`集市日。今年流行按对角线报价，正方形们占了便宜。`, `Market day. Quoting prices by the diagonal is in fashion this year, which favours the squares.`),
  },
  foil: {
    village: ([a, m]) => tr(`${a}们又拼好了一个街区。拼完才发现是上一个街区的镜像，它们决定两个都留着。`, `The ${m} finished another district, then noticed it was a mirror image of the last one. They decided to keep both.`),
    harvest: () => tr(`余温节又到了。今年剩下的热量少了一点，残影们挤得更紧了一点。`, `Afterglow Day again. There was a little less heat left this year, so the shadows huddled a little closer.`),
    north: () => tr(`关于「上」的争论还在继续。有一派提议先把「下」定下来，结果谁也记不起「下」是什么样。`, `The argument about "up" continues. One faction proposed settling "down" first, only to find nobody could remember what down looked like.`),
    road: () => tr(`又有两块影子接上了。接缝两边的残影说，它们以前住在同一条街，从没见过面。`, `Two more shadows were joined. The ones along the seam say they used to live on the same street and never met.`),
    market: () => tr(`交换日。今年最抢手的是一块完整的窗框，据说透过它能看见压平之前。`, `Exchange day. This year's most sought-after piece was a complete window frame; supposedly you can see through it to before the flattening.`),
    map: () => tr(`考古队又往外挖了一层。挖出来的东西太平了，它们差点登记成空白。`, `The excavators dug out another layer. What they found was so flat they almost logged it as blank.`),
  },
  dune: {
    village: ([a, m]) => tr(`${a}们又挖了一个巢穴，挖到一半碰上了别人的旧巢。它们把两个打通，按辈分分了房间。`, `The ${m} dug another warren and halfway through broke into someone's old one. They joined the two and allocated chambers by seniority.`),
    harvest: () => tr(`又一次香料潮。年轻的沙虫第一次见，吃得太急，身上的纹都变了颜色。`, `Another spice tide. The young worms, seeing their first, ate too fast and their stripes changed colour.`),
    north: () => tr(`沙丘往哪边走的争论交给了下一代。下一代醒来的时候，沙丘已经走到别处去了。`, `The dispute over the dunes' direction passed to the next generation. By the time they woke, the dunes had moved somewhere else.`),
    road: () => tr(`又一条隧道挖通了。开通那天，两头的沙虫在中间擦肩而过，谁也没让谁。`, `Another tunnel broke through. On opening day the worms from each end squeezed past each other in the middle; neither gave way.`),
    market: () => tr(`交易季。今年一张好看的皮能换三口香料，去年只能换两口。长老说这叫繁荣。`, `Trading season. A handsome skin fetches three mouthfuls of spice this year, up from two. The elders call this prosperity.`),
    map: () => tr(`又一条侦察的沙虫回来了，带回的图比上一张大一圈。它说远处的沙子比这边细。`, `Another scout worm returned with a map one ring larger than the last. It reports the sand out there is finer.`),
  },
  solaris: {
    village: () => tr(`海又造了一片形状，和上一片几乎一样，只在角上多了一个我走路的姿势。`, `The ocean built another shape, nearly identical to the last, except one corner has taken on my gait.`),
    harvest: () => tr(`又是平静的一季。有几个念头在镜面上看得太久，忘了自己本来要想什么。`, `Another calm season. A few thoughts stared into the mirror too long and forgot what they had meant to think.`),
    north: () => tr(`潮水又分成了两边。中间那片滩地上开始长东西，海没有认领。`, `The tide split both ways again. Things have started growing on the beach in between; the ocean hasn't claimed them.`),
    road: () => tr(`又一道水拱架了起来。拱底下的念头说，走过去的时候能听见拱在想事情。`, `Another water arch went up. The thoughts beneath it say you can hear it thinking as you pass.`),
    market: () => tr(`又一阵大浪。这次搅得太匀，有几个念头分不出来了，海就让它们合成了一个。`, `Another great wave. It churned so evenly that a few thoughts couldn't be told apart, so the ocean let them merge.`),
    map: () => tr(`海又伸出一条触须。这一条伸得太远，回来的时候带着别处的温度。`, `The ocean sent out another tendril. This one reached so far it came back carrying the temperature of somewhere else.`),
  },
  crystal: {
    village: ([a, m]) => tr(`${a}们又长出一簇。这一簇长得太快，有点歪。老晶簇们看了很久，决定什么也不说。`, `The ${m} grew another cluster. It grew too fast and came out slightly crooked. The older clusters looked at it for a long time and decided to say nothing.`),
    harvest: () => tr(`又是浓溶液的一季。有几颗晶体长得太贪，把旁边的也包了进去，事后都说是对方先靠过来的。`, `Another rich season. A few crystals grew greedily and engulfed their neighbours; afterwards each said the other had leaned in first.`),
    north: () => tr(`方向之争又起了一次。这次僵持出来的结比上次小，大家认为这是一种进步。`, `The direction dispute flared again. This time the knot it produced was smaller, which everyone regarded as progress.`),
    road: () => tr(`又一道晶桥长成了。桥中间有一处颜色不一样，两边都说那是对方的杂质。`, `Another crystal bridge formed. There's an off-colour patch in the middle; each side says it's the other's impurity.`),
    market: () => tr(`离子交换又开始了。有一颗换得太多，已经说不清自己原来是什么颜色。`, `Ion exchange resumed. One crystal traded so much it can no longer say what colour it started as.`),
    map: () => tr(`又一根晶须长了出去，比上一根更细，也更远。它照亮的地方，边缘带着一点彩虹。`, `Another whisker grew out, finer and longer than the last. The areas it lit up have a faint rainbow at the edges.`),
  },
  pcb: {
    village: ([a, m]) => tr(`${a}们又起了一个进程。它继承了上一个的全部内存，也继承了上一个的全部问题。`, `The ${m} spawned another process. It inherited all of its parent's memory, and all of its parent's problems.`),
    harvest: () => tr(`又一个稳压的季节。所有进程都跑满了负载，风扇第一次转到了最高档。`, `Another season of clean power. Every process ran at full load, and the fan hit top speed for the first time.`),
    north: () => tr(`字节序之争又开了一次会。会议决定加一层转换，转换层自己用的是第三种字节序。`, `The byte-order dispute held another meeting. They agreed to add a conversion layer. The conversion layer uses a third byte order.`),
    road: () => tr(`又一条总线拉通了。上线第一天就塞满了，工程师说这证明需求是真实的。`, `Another bus came up. It was saturated on day one, which the engineers say proves the demand was real.`),
    market: () => tr(`缓存又一次命中了新高。借出去的数据还是没人还，账面上一切都很好。`, `Another cache-hit record. The borrowed data still hasn't been returned, and on paper everything looks fine.`),
    map: () => tr(`探测进程又扫了一段地址。扫到最后一格的时候，它收到了一个没见过的回应。`, `The probe scanned another address range. At the last address it got a reply it had never seen before.`),
  },
  ink: {
    village: ([a, m]) => tr(`${a}们又添了一处院落。院墙画得太直，旁边的老小人说不像这幅画的笔法。`, `The ${m} added another courtyard. The walls came out too straight; the older figures say it doesn't match the brushwork.`),
    harvest: () => tr(`又下了一场雨。这回雨下进了画里，小人们第一次撑起了伞，伞也只有一笔。`, `Rain again. This time it fell inside the painting, and the figures opened umbrellas for the first time. Each umbrella is one stroke.`),
    north: () => tr(`看画方向的争论传到了下一代。下一代干脆把画卷起来，从中间开始看。`, `The reading-direction dispute passed to the next generation, who simply rolled up the scroll and started from the middle.`),
    road: () => tr(`又画了一座小桥，只画了一半，另一半在雾里。小人们走到雾边就停下来等。`, `Another little bridge was painted, only half of it; the other half is in the mist. The figures walk to the edge of the mist and wait.`),
    market: () => tr(`又是集市日。今年多了一个卖留白的摊子，生意很好。`, `Market day again. This year there's a stall selling blank space. Business is brisk.`),
    map: () => tr(`又一条船划进了空白处。这回划得太远，回来的时候船上多了几座别人画的山。`, `Another boat went into the blank. It went so far it came back carrying a few mountains somebody else had painted.`),
  },
  blueprint: {
    village: ([a, m]) => tr(`${a}们又围了一个图块。编号和上一个重了，只好在后面加一个「A」。`, `The ${m} enclosed another block. Its number clashed with the last one, so they added an "A".`),
    harvest: () => tr(`又一季没有修改意见。几个标注闲不住，自己给自己加了一道引出线。`, `Another season without review comments. A few restless labels added leader lines to themselves.`),
    north: () => tr(`指北针之争再次开会。会议决定在第三个角再画一个，取三个的平均值。`, `The north-arrow dispute met again. They decided to add a third arrow in another corner and take the average.`),
    road: () => tr(`又画了一条走廊，宽度又是最小值。消防审查在旁边写了三个问号。`, `Another corridor was drawn, again at minimum width. The fire inspector wrote three question marks beside it.`),
    market: () => tr(`标准件库又更新了。这次换了单位制，所有尺寸一夜之间都变长了。`, `The standard parts library updated again. This time the units changed, and every dimension got longer overnight.`),
    map: () => tr(`测量员这回走得更远，远到图框扩了一圈，把测量员自己也框了进去。`, `The surveyor went further out this time, far enough that the border expanded to include the surveyor too.`),
  },
  slide: {
    village: ([a, m]) => tr(`${a}们又聚成一团。新的细胞团长得比老的快，老的决定不去管它。`, `The ${m} formed another colony. The new one grows faster than the old ones, which have decided not to interfere.`),
    harvest: () => tr(`培养液又换了一次，这回温度也调高了一点。细胞们分裂到忘了数。`, `The medium was changed again, a degree warmer this time. The cells divided until they lost count.`),
    north: () => tr(`极化之争又来了。这一次两边各退一步，中间多出了一层谁也不认的细胞。`, `The polarity dispute returned. This time each side gave a little, and a layer of cells nobody claims appeared in between.`),
    road: () => tr(`又长出了一条血管，比上一条细。两边为该不该给它起名字争了一阵。`, `Another blood vessel grew, finer than the last. The two sides argued briefly over whether it deserved a name.`),
    market: () => tr(`线粒体又交换了一轮。有几个细胞换得太多，线粒体比自己还大。`, `Another round of mitochondria swapping. A few cells traded so much their mitochondria outgrew them.`),
    map: () => tr(`白细胞又巡逻了一圈，这一圈比上次远。回来的时候，其中一个身上沾着别处的组织。`, `The white cells patrolled again, further this time. One came back with someone else's tissue stuck to it.`),
  },
};
for (const k in MORE) for (const id in MORE[k]) CIV_EV[k].ev[id] = [].concat(CIV_EV[k].ev[id], MORE[k][id]);
for (const k in CIV_EV) Object.assign(CIVS[k], CIV_EV[k]);
const CIV = CIVS[G.theme] || CIVS.earth;
